/**
 * Auditable rejected-candidate report for Open specific-identity vocabulary generation (v0.7).
 * Deterministic fixture for inspection — not runtime scoring input.
 *
 * Rejection content SHA-256: 3b125ed759c032ae15a8c588a4e8edd6c475e0597a5596c736e049ff8ddfc04d
 */
export const OPEN_SPECIFIC_IDENTITY_REJECTION_META = {
  methodologyVersion: 'v0.7',
  totalRejected: 1114,
  countsByReason: {
    placeholder_name: 799,
    code_like: 127,
    annotation_admin: 155,
    class_labelled: 13,
    parenthetical_not_allowlisted: 7,
    blocked_shell_exact: 13,
    too_short: 0,
  },
  contentSha256: '3b125ed759c032ae15a8c588a4e8edd6c475e0597a5596c736e049ff8ddfc04d',
} as const;

export type OpenSpecificIdentityRejectionReason =
  | 'placeholder_name'
  | 'code_like'
  | 'annotation_admin'
  | 'class_labelled'
  | 'parenthetical_not_allowlisted'
  | 'blocked_shell_exact'
  | 'too_short';

export interface OpenSpecificIdentityRejection {
  phrase: string;
  reason: OpenSpecificIdentityRejectionReason;
  source: string;
}

/** Full rejected-candidate ledger (sorted by reason, then phrase). */
export const OPEN_SPECIFIC_IDENTITY_REJECTIONS: readonly OpenSpecificIdentityRejection[] =
  Object.freeze([
    {"phrase":"additional variant","reason":"annotation_admin","source":"name-paren:Calcium Lactate (additional variant)"},
    {"phrase":"alternative","reason":"annotation_admin","source":"name-paren:Calcium Citrate (alternative)"},
    {"phrase":"alternative","reason":"annotation_admin","source":"name-paren:Calcium Lactate (alternative)"},
    {"phrase":"alternative","reason":"annotation_admin","source":"name-paren:Titanium Dioxide (alternative)"},
    {"phrase":"ammonia","reason":"annotation_admin","source":"name-paren:Caramel III (Ammonia)"},
    {"phrase":"ammonia sulfite","reason":"annotation_admin","source":"name-paren:Caramel IV (Ammonia Sulfite)"},
    {"phrase":"another variant","reason":"annotation_admin","source":"name-paren:Ammonium Tartrate (another variant)"},
    {"phrase":"another variant","reason":"annotation_admin","source":"name-paren:Calcium Lactate (another variant)"},
    {"phrase":"another variant","reason":"annotation_admin","source":"name-paren:Calcium Tartrate (another variant)"},
    {"phrase":"caustic sulfite","reason":"annotation_admin","source":"name-paren:Caramel II (Caustic Sulfite)"},
    {"phrase":"plain","reason":"annotation_admin","source":"name-paren:Caramel I (Plain)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E700 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E701 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E702 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E703 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E704 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E705 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E706 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E707 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E708 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E709 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E710 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E711 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E712 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E713 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E714 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E715 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E716 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E717 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E718 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E719 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E720 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E721 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E722 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E723 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E724 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E725 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E726 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E727 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E728 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E729 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E730 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E731 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E732 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E733 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E734 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E735 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E736 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E737 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E738 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E739 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E740 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E741 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E742 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E743 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E744 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E745 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E746 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E747 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E748 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E749 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E750 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E751 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E752 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E753 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E754 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E755 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E756 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E757 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E758 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E759 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E760 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E761 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E762 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E763 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E764 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E765 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E766 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E767 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E768 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E769 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E770 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E771 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E772 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E773 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E774 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E775 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E776 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E777 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E778 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E779 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E780 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E781 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E782 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E783 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E784 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E785 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E786 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E787 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E788 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E789 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E790 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E791 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E792 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E793 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E794 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E795 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E796 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E797 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E798 (Reserved for Antibiotics)"},
    {"phrase":"reserved for antibiotics","reason":"annotation_admin","source":"name-paren:E799 (Reserved for Antibiotics)"},
    {"phrase":"unspecified","reason":"annotation_admin","source":"name-paren:Caramel Color (unspecified)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Ammonium Citrate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Ammonium Fumarate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Ammonium Tartrate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Brown FK (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Brown HT (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Calcium Ascorbate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Calcium Citrate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Calcium Fumarate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Calcium Hydrogen Sulfite (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Calcium Lactate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Calcium Malate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Calcium Nitrite (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Calcium Propionate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Calcium Sorbate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Calcium Stearoyl Lactylate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Calcium Stearoyl-2-Lactylate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Calcium Sulfite (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Calcium Tartrate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Diphosphates (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Erythorbic Acid (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Ethyl p-Hydroxybenzoate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Gelatin (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Green S (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Polyphosphates (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Potassium Citrate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Potassium Lactate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Potassium Metabisulfite (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Potassium Propionate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Rosemary Extract (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Sodium Ascorbate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Sodium Citrate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Sodium Erythorbate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Sodium Lactate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Sodium Metabisulfite (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Sodium Nitrate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Sodium Nitrite (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Sodium Propionate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Sodium Stearoyl Lactylate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Stearyl Citrate (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Triphosphates (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Yellow 2G (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Yellow AB Lake (variant)"},
    {"phrase":"variant","reason":"annotation_admin","source":"name-paren:Yellow OB Lake (variant)"},
    {"phrase":"color","reason":"blocked_shell_exact","source":"bodyMvp:color (allura red ac)"},
    {"phrase":"color","reason":"blocked_shell_exact","source":"bodyMvp:color (sunset yellow fcf)"},
    {"phrase":"color","reason":"blocked_shell_exact","source":"bodyMvp:color (tartrazine)"},
    {"phrase":"color","reason":"blocked_shell_exact","source":"bodyMvp:color (titanium dioxide)"},
    {"phrase":"color","reason":"blocked_shell_exact","source":"name-paren:Calcium Oxide (color)"},
    {"phrase":"color","reason":"blocked_shell_exact","source":"name-paren:Magnesium Oxide (color)"},
    {"phrase":"colour","reason":"blocked_shell_exact","source":"bodyMvp:colour (allura red ac)"},
    {"phrase":"colour","reason":"blocked_shell_exact","source":"bodyMvp:colour (sunset yellow fcf)"},
    {"phrase":"colour","reason":"blocked_shell_exact","source":"bodyMvp:colour (tartrazine)"},
    {"phrase":"colour","reason":"blocked_shell_exact","source":"bodyMvp:colour (titanium dioxide)"},
    {"phrase":"preservative","reason":"blocked_shell_exact","source":"bodyMvp:preservative (sodium nitrite)"},
    {"phrase":"sweetener","reason":"blocked_shell_exact","source":"bodyMvp:sweetener (951)"},
    {"phrase":"sweetener","reason":"blocked_shell_exact","source":"bodyMvp:sweetener (aspartame)"},
    {"phrase":"acid green 25","reason":"class_labelled","source":"name-base:Acid Green 25"},
    {"phrase":"acid treated starch","reason":"class_labelled","source":"name-base:Acid-Treated Starch"},
    {"phrase":"color allura red ac","reason":"class_labelled","source":"bodyMvp-composed:color (allura red ac)"},
    {"phrase":"color sunset yellow fcf","reason":"class_labelled","source":"bodyMvp-composed:color (sunset yellow fcf)"},
    {"phrase":"color tartrazine","reason":"class_labelled","source":"bodyMvp-composed:color (tartrazine)"},
    {"phrase":"color titanium dioxide","reason":"class_labelled","source":"bodyMvp-composed:color (titanium dioxide)"},
    {"phrase":"colour allura red ac","reason":"class_labelled","source":"bodyMvp-composed:colour (allura red ac)"},
    {"phrase":"colour sunset yellow fcf","reason":"class_labelled","source":"bodyMvp-composed:colour (sunset yellow fcf)"},
    {"phrase":"colour tartrazine","reason":"class_labelled","source":"bodyMvp-composed:colour (tartrazine)"},
    {"phrase":"colour titanium dioxide","reason":"class_labelled","source":"bodyMvp-composed:colour (titanium dioxide)"},
    {"phrase":"enzyme treated starch","reason":"class_labelled","source":"name-base:Enzyme-Treated Starch"},
    {"phrase":"preservative sodium nitrite","reason":"class_labelled","source":"bodyMvp-composed:preservative (sodium nitrite)"},
    {"phrase":"sweetener aspartame","reason":"class_labelled","source":"bodyMvp-composed:sweetener (aspartame)"},
    {"phrase":"color 102","reason":"code_like","source":"bodyMvp:color (102)"},
    {"phrase":"color 110","reason":"code_like","source":"bodyMvp:color (110)"},
    {"phrase":"color 129","reason":"code_like","source":"bodyMvp:color (129)"},
    {"phrase":"color 171","reason":"code_like","source":"bodyMvp:color (171)"},
    {"phrase":"colour 102","reason":"code_like","source":"bodyMvp:colour (102)"},
    {"phrase":"colour 110","reason":"code_like","source":"bodyMvp:colour (110)"},
    {"phrase":"colour 129","reason":"code_like","source":"bodyMvp:colour (129)"},
    {"phrase":"colour 171","reason":"code_like","source":"bodyMvp:colour (171)"},
    {"phrase":"e 102","reason":"code_like","source":"bodyMvp:e 102"},
    {"phrase":"e 102","reason":"code_like","source":"bodyMvp:e-102"},
    {"phrase":"e 110","reason":"code_like","source":"bodyMvp:e 110"},
    {"phrase":"e 110","reason":"code_like","source":"bodyMvp:e-110"},
    {"phrase":"e 129","reason":"code_like","source":"bodyMvp:e 129"},
    {"phrase":"e 129","reason":"code_like","source":"bodyMvp:e-129"},
    {"phrase":"e 171","reason":"code_like","source":"bodyMvp:e 171"},
    {"phrase":"e 171","reason":"code_like","source":"bodyMvp:e-171"},
    {"phrase":"e 250","reason":"code_like","source":"bodyMvp:e 250"},
    {"phrase":"e 250","reason":"code_like","source":"bodyMvp:e-250"},
    {"phrase":"e 951","reason":"code_like","source":"bodyMvp:e 951"},
    {"phrase":"e 951","reason":"code_like","source":"bodyMvp:e-951"},
    {"phrase":"e102","reason":"code_like","source":"bodyMvp:e102"},
    {"phrase":"e110","reason":"code_like","source":"bodyMvp:e110"},
    {"phrase":"e129","reason":"code_like","source":"bodyMvp:e129"},
    {"phrase":"e171","reason":"code_like","source":"bodyMvp:e171"},
    {"phrase":"e250","reason":"code_like","source":"bodyMvp:e250"},
    {"phrase":"e700","reason":"code_like","source":"name-base:E700 (Reserved for Antibiotics)"},
    {"phrase":"e701","reason":"code_like","source":"name-base:E701 (Reserved for Antibiotics)"},
    {"phrase":"e702","reason":"code_like","source":"name-base:E702 (Reserved for Antibiotics)"},
    {"phrase":"e703","reason":"code_like","source":"name-base:E703 (Reserved for Antibiotics)"},
    {"phrase":"e704","reason":"code_like","source":"name-base:E704 (Reserved for Antibiotics)"},
    {"phrase":"e705","reason":"code_like","source":"name-base:E705 (Reserved for Antibiotics)"},
    {"phrase":"e706","reason":"code_like","source":"name-base:E706 (Reserved for Antibiotics)"},
    {"phrase":"e707","reason":"code_like","source":"name-base:E707 (Reserved for Antibiotics)"},
    {"phrase":"e708","reason":"code_like","source":"name-base:E708 (Reserved for Antibiotics)"},
    {"phrase":"e709","reason":"code_like","source":"name-base:E709 (Reserved for Antibiotics)"},
    {"phrase":"e710","reason":"code_like","source":"name-base:E710 (Reserved for Antibiotics)"},
    {"phrase":"e711","reason":"code_like","source":"name-base:E711 (Reserved for Antibiotics)"},
    {"phrase":"e712","reason":"code_like","source":"name-base:E712 (Reserved for Antibiotics)"},
    {"phrase":"e713","reason":"code_like","source":"name-base:E713 (Reserved for Antibiotics)"},
    {"phrase":"e714","reason":"code_like","source":"name-base:E714 (Reserved for Antibiotics)"},
    {"phrase":"e715","reason":"code_like","source":"name-base:E715 (Reserved for Antibiotics)"},
    {"phrase":"e716","reason":"code_like","source":"name-base:E716 (Reserved for Antibiotics)"},
    {"phrase":"e717","reason":"code_like","source":"name-base:E717 (Reserved for Antibiotics)"},
    {"phrase":"e718","reason":"code_like","source":"name-base:E718 (Reserved for Antibiotics)"},
    {"phrase":"e719","reason":"code_like","source":"name-base:E719 (Reserved for Antibiotics)"},
    {"phrase":"e720","reason":"code_like","source":"name-base:E720 (Reserved for Antibiotics)"},
    {"phrase":"e721","reason":"code_like","source":"name-base:E721 (Reserved for Antibiotics)"},
    {"phrase":"e722","reason":"code_like","source":"name-base:E722 (Reserved for Antibiotics)"},
    {"phrase":"e723","reason":"code_like","source":"name-base:E723 (Reserved for Antibiotics)"},
    {"phrase":"e724","reason":"code_like","source":"name-base:E724 (Reserved for Antibiotics)"},
    {"phrase":"e725","reason":"code_like","source":"name-base:E725 (Reserved for Antibiotics)"},
    {"phrase":"e726","reason":"code_like","source":"name-base:E726 (Reserved for Antibiotics)"},
    {"phrase":"e727","reason":"code_like","source":"name-base:E727 (Reserved for Antibiotics)"},
    {"phrase":"e728","reason":"code_like","source":"name-base:E728 (Reserved for Antibiotics)"},
    {"phrase":"e729","reason":"code_like","source":"name-base:E729 (Reserved for Antibiotics)"},
    {"phrase":"e730","reason":"code_like","source":"name-base:E730 (Reserved for Antibiotics)"},
    {"phrase":"e731","reason":"code_like","source":"name-base:E731 (Reserved for Antibiotics)"},
    {"phrase":"e732","reason":"code_like","source":"name-base:E732 (Reserved for Antibiotics)"},
    {"phrase":"e733","reason":"code_like","source":"name-base:E733 (Reserved for Antibiotics)"},
    {"phrase":"e734","reason":"code_like","source":"name-base:E734 (Reserved for Antibiotics)"},
    {"phrase":"e735","reason":"code_like","source":"name-base:E735 (Reserved for Antibiotics)"},
    {"phrase":"e736","reason":"code_like","source":"name-base:E736 (Reserved for Antibiotics)"},
    {"phrase":"e737","reason":"code_like","source":"name-base:E737 (Reserved for Antibiotics)"},
    {"phrase":"e738","reason":"code_like","source":"name-base:E738 (Reserved for Antibiotics)"},
    {"phrase":"e739","reason":"code_like","source":"name-base:E739 (Reserved for Antibiotics)"},
    {"phrase":"e740","reason":"code_like","source":"name-base:E740 (Reserved for Antibiotics)"},
    {"phrase":"e741","reason":"code_like","source":"name-base:E741 (Reserved for Antibiotics)"},
    {"phrase":"e742","reason":"code_like","source":"name-base:E742 (Reserved for Antibiotics)"},
    {"phrase":"e743","reason":"code_like","source":"name-base:E743 (Reserved for Antibiotics)"},
    {"phrase":"e744","reason":"code_like","source":"name-base:E744 (Reserved for Antibiotics)"},
    {"phrase":"e745","reason":"code_like","source":"name-base:E745 (Reserved for Antibiotics)"},
    {"phrase":"e746","reason":"code_like","source":"name-base:E746 (Reserved for Antibiotics)"},
    {"phrase":"e747","reason":"code_like","source":"name-base:E747 (Reserved for Antibiotics)"},
    {"phrase":"e748","reason":"code_like","source":"name-base:E748 (Reserved for Antibiotics)"},
    {"phrase":"e749","reason":"code_like","source":"name-base:E749 (Reserved for Antibiotics)"},
    {"phrase":"e750","reason":"code_like","source":"name-base:E750 (Reserved for Antibiotics)"},
    {"phrase":"e751","reason":"code_like","source":"name-base:E751 (Reserved for Antibiotics)"},
    {"phrase":"e752","reason":"code_like","source":"name-base:E752 (Reserved for Antibiotics)"},
    {"phrase":"e753","reason":"code_like","source":"name-base:E753 (Reserved for Antibiotics)"},
    {"phrase":"e754","reason":"code_like","source":"name-base:E754 (Reserved for Antibiotics)"},
    {"phrase":"e755","reason":"code_like","source":"name-base:E755 (Reserved for Antibiotics)"},
    {"phrase":"e756","reason":"code_like","source":"name-base:E756 (Reserved for Antibiotics)"},
    {"phrase":"e757","reason":"code_like","source":"name-base:E757 (Reserved for Antibiotics)"},
    {"phrase":"e758","reason":"code_like","source":"name-base:E758 (Reserved for Antibiotics)"},
    {"phrase":"e759","reason":"code_like","source":"name-base:E759 (Reserved for Antibiotics)"},
    {"phrase":"e760","reason":"code_like","source":"name-base:E760 (Reserved for Antibiotics)"},
    {"phrase":"e761","reason":"code_like","source":"name-base:E761 (Reserved for Antibiotics)"},
    {"phrase":"e762","reason":"code_like","source":"name-base:E762 (Reserved for Antibiotics)"},
    {"phrase":"e763","reason":"code_like","source":"name-base:E763 (Reserved for Antibiotics)"},
    {"phrase":"e764","reason":"code_like","source":"name-base:E764 (Reserved for Antibiotics)"},
    {"phrase":"e765","reason":"code_like","source":"name-base:E765 (Reserved for Antibiotics)"},
    {"phrase":"e766","reason":"code_like","source":"name-base:E766 (Reserved for Antibiotics)"},
    {"phrase":"e767","reason":"code_like","source":"name-base:E767 (Reserved for Antibiotics)"},
    {"phrase":"e768","reason":"code_like","source":"name-base:E768 (Reserved for Antibiotics)"},
    {"phrase":"e769","reason":"code_like","source":"name-base:E769 (Reserved for Antibiotics)"},
    {"phrase":"e770","reason":"code_like","source":"name-base:E770 (Reserved for Antibiotics)"},
    {"phrase":"e771","reason":"code_like","source":"name-base:E771 (Reserved for Antibiotics)"},
    {"phrase":"e772","reason":"code_like","source":"name-base:E772 (Reserved for Antibiotics)"},
    {"phrase":"e773","reason":"code_like","source":"name-base:E773 (Reserved for Antibiotics)"},
    {"phrase":"e774","reason":"code_like","source":"name-base:E774 (Reserved for Antibiotics)"},
    {"phrase":"e775","reason":"code_like","source":"name-base:E775 (Reserved for Antibiotics)"},
    {"phrase":"e776","reason":"code_like","source":"name-base:E776 (Reserved for Antibiotics)"},
    {"phrase":"e777","reason":"code_like","source":"name-base:E777 (Reserved for Antibiotics)"},
    {"phrase":"e778","reason":"code_like","source":"name-base:E778 (Reserved for Antibiotics)"},
    {"phrase":"e779","reason":"code_like","source":"name-base:E779 (Reserved for Antibiotics)"},
    {"phrase":"e780","reason":"code_like","source":"name-base:E780 (Reserved for Antibiotics)"},
    {"phrase":"e781","reason":"code_like","source":"name-base:E781 (Reserved for Antibiotics)"},
    {"phrase":"e782","reason":"code_like","source":"name-base:E782 (Reserved for Antibiotics)"},
    {"phrase":"e783","reason":"code_like","source":"name-base:E783 (Reserved for Antibiotics)"},
    {"phrase":"e784","reason":"code_like","source":"name-base:E784 (Reserved for Antibiotics)"},
    {"phrase":"e785","reason":"code_like","source":"name-base:E785 (Reserved for Antibiotics)"},
    {"phrase":"e786","reason":"code_like","source":"name-base:E786 (Reserved for Antibiotics)"},
    {"phrase":"e787","reason":"code_like","source":"name-base:E787 (Reserved for Antibiotics)"},
    {"phrase":"e788","reason":"code_like","source":"name-base:E788 (Reserved for Antibiotics)"},
    {"phrase":"e789","reason":"code_like","source":"name-base:E789 (Reserved for Antibiotics)"},
    {"phrase":"e790","reason":"code_like","source":"name-base:E790 (Reserved for Antibiotics)"},
    {"phrase":"e791","reason":"code_like","source":"name-base:E791 (Reserved for Antibiotics)"},
    {"phrase":"e792","reason":"code_like","source":"name-base:E792 (Reserved for Antibiotics)"},
    {"phrase":"e793","reason":"code_like","source":"name-base:E793 (Reserved for Antibiotics)"},
    {"phrase":"e794","reason":"code_like","source":"name-base:E794 (Reserved for Antibiotics)"},
    {"phrase":"e795","reason":"code_like","source":"name-base:E795 (Reserved for Antibiotics)"},
    {"phrase":"e796","reason":"code_like","source":"name-base:E796 (Reserved for Antibiotics)"},
    {"phrase":"e797","reason":"code_like","source":"name-base:E797 (Reserved for Antibiotics)"},
    {"phrase":"e798","reason":"code_like","source":"name-base:E798 (Reserved for Antibiotics)"},
    {"phrase":"e799","reason":"code_like","source":"name-base:E799 (Reserved for Antibiotics)"},
    {"phrase":"e951","reason":"code_like","source":"bodyMvp:e951"},
    {"phrase":"preservative 250","reason":"code_like","source":"bodyMvp:preservative (250)"},
    {"phrase":"alpha beta gamma","reason":"parenthetical_not_allowlisted","source":"name-paren:Carotenes (Alpha, Beta, Gamma)"},
    {"phrase":"butylated hydroxyanisole","reason":"parenthetical_not_allowlisted","source":"name-paren:BHA (Butylated Hydroxyanisole)"},
    {"phrase":"butylated hydroxytoluene","reason":"parenthetical_not_allowlisted","source":"name-paren:BHT (Butylated Hydroxytoluene)"},
    {"phrase":"stevia","reason":"parenthetical_not_allowlisted","source":"name-paren:Steviol Glycosides (Stevia)"},
    {"phrase":"tertiary butylhydroquinone","reason":"parenthetical_not_allowlisted","source":"name-paren:TBHQ (Tertiary Butylhydroquinone)"},
    {"phrase":"vitamin c","reason":"parenthetical_not_allowlisted","source":"name-paren:Ascorbic Acid (Vitamin C)"},
    {"phrase":"vitamin e","reason":"parenthetical_not_allowlisted","source":"name-paren:Tocopherols (Vitamin E)"},
    {"phrase":"e1000","reason":"placeholder_name","source":"name:E1000"},
    {"phrase":"e1001","reason":"placeholder_name","source":"name:E1001"},
    {"phrase":"e1002","reason":"placeholder_name","source":"name:E1002"},
    {"phrase":"e1003","reason":"placeholder_name","source":"name:E1003"},
    {"phrase":"e1004","reason":"placeholder_name","source":"name:E1004"},
    {"phrase":"e1005","reason":"placeholder_name","source":"name:E1005"},
    {"phrase":"e1006","reason":"placeholder_name","source":"name:E1006"},
    {"phrase":"e1007","reason":"placeholder_name","source":"name:E1007"},
    {"phrase":"e1008","reason":"placeholder_name","source":"name:E1008"},
    {"phrase":"e1009","reason":"placeholder_name","source":"name:E1009"},
    {"phrase":"e1010","reason":"placeholder_name","source":"name:E1010"},
    {"phrase":"e1011","reason":"placeholder_name","source":"name:E1011"},
    {"phrase":"e1012","reason":"placeholder_name","source":"name:E1012"},
    {"phrase":"e1013","reason":"placeholder_name","source":"name:E1013"},
    {"phrase":"e1014","reason":"placeholder_name","source":"name:E1014"},
    {"phrase":"e1015","reason":"placeholder_name","source":"name:E1015"},
    {"phrase":"e1016","reason":"placeholder_name","source":"name:E1016"},
    {"phrase":"e1017","reason":"placeholder_name","source":"name:E1017"},
    {"phrase":"e1018","reason":"placeholder_name","source":"name:E1018"},
    {"phrase":"e1019","reason":"placeholder_name","source":"name:E1019"},
    {"phrase":"e1020","reason":"placeholder_name","source":"name:E1020"},
    {"phrase":"e1021","reason":"placeholder_name","source":"name:E1021"},
    {"phrase":"e1022","reason":"placeholder_name","source":"name:E1022"},
    {"phrase":"e1023","reason":"placeholder_name","source":"name:E1023"},
    {"phrase":"e1024","reason":"placeholder_name","source":"name:E1024"},
    {"phrase":"e1025","reason":"placeholder_name","source":"name:E1025"},
    {"phrase":"e1026","reason":"placeholder_name","source":"name:E1026"},
    {"phrase":"e1027","reason":"placeholder_name","source":"name:E1027"},
    {"phrase":"e1028","reason":"placeholder_name","source":"name:E1028"},
    {"phrase":"e1029","reason":"placeholder_name","source":"name:E1029"},
    {"phrase":"e1030","reason":"placeholder_name","source":"name:E1030"},
    {"phrase":"e1031","reason":"placeholder_name","source":"name:E1031"},
    {"phrase":"e1032","reason":"placeholder_name","source":"name:E1032"},
    {"phrase":"e1033","reason":"placeholder_name","source":"name:E1033"},
    {"phrase":"e1034","reason":"placeholder_name","source":"name:E1034"},
    {"phrase":"e1035","reason":"placeholder_name","source":"name:E1035"},
    {"phrase":"e1036","reason":"placeholder_name","source":"name:E1036"},
    {"phrase":"e1037","reason":"placeholder_name","source":"name:E1037"},
    {"phrase":"e1038","reason":"placeholder_name","source":"name:E1038"},
    {"phrase":"e1039","reason":"placeholder_name","source":"name:E1039"},
    {"phrase":"e1040","reason":"placeholder_name","source":"name:E1040"},
    {"phrase":"e1041","reason":"placeholder_name","source":"name:E1041"},
    {"phrase":"e1042","reason":"placeholder_name","source":"name:E1042"},
    {"phrase":"e1043","reason":"placeholder_name","source":"name:E1043"},
    {"phrase":"e1044","reason":"placeholder_name","source":"name:E1044"},
    {"phrase":"e1045","reason":"placeholder_name","source":"name:E1045"},
    {"phrase":"e1046","reason":"placeholder_name","source":"name:E1046"},
    {"phrase":"e1047","reason":"placeholder_name","source":"name:E1047"},
    {"phrase":"e1048","reason":"placeholder_name","source":"name:E1048"},
    {"phrase":"e1049","reason":"placeholder_name","source":"name:E1049"},
    {"phrase":"e1050","reason":"placeholder_name","source":"name:E1050"},
    {"phrase":"e1051","reason":"placeholder_name","source":"name:E1051"},
    {"phrase":"e1052","reason":"placeholder_name","source":"name:E1052"},
    {"phrase":"e1053","reason":"placeholder_name","source":"name:E1053"},
    {"phrase":"e1054","reason":"placeholder_name","source":"name:E1054"},
    {"phrase":"e1055","reason":"placeholder_name","source":"name:E1055"},
    {"phrase":"e1056","reason":"placeholder_name","source":"name:E1056"},
    {"phrase":"e1057","reason":"placeholder_name","source":"name:E1057"},
    {"phrase":"e1058","reason":"placeholder_name","source":"name:E1058"},
    {"phrase":"e1059","reason":"placeholder_name","source":"name:E1059"},
    {"phrase":"e1060","reason":"placeholder_name","source":"name:E1060"},
    {"phrase":"e1061","reason":"placeholder_name","source":"name:E1061"},
    {"phrase":"e1062","reason":"placeholder_name","source":"name:E1062"},
    {"phrase":"e1063","reason":"placeholder_name","source":"name:E1063"},
    {"phrase":"e1064","reason":"placeholder_name","source":"name:E1064"},
    {"phrase":"e1065","reason":"placeholder_name","source":"name:E1065"},
    {"phrase":"e1066","reason":"placeholder_name","source":"name:E1066"},
    {"phrase":"e1067","reason":"placeholder_name","source":"name:E1067"},
    {"phrase":"e1068","reason":"placeholder_name","source":"name:E1068"},
    {"phrase":"e1069","reason":"placeholder_name","source":"name:E1069"},
    {"phrase":"e1070","reason":"placeholder_name","source":"name:E1070"},
    {"phrase":"e1071","reason":"placeholder_name","source":"name:E1071"},
    {"phrase":"e1072","reason":"placeholder_name","source":"name:E1072"},
    {"phrase":"e1073","reason":"placeholder_name","source":"name:E1073"},
    {"phrase":"e1074","reason":"placeholder_name","source":"name:E1074"},
    {"phrase":"e1075","reason":"placeholder_name","source":"name:E1075"},
    {"phrase":"e1076","reason":"placeholder_name","source":"name:E1076"},
    {"phrase":"e1077","reason":"placeholder_name","source":"name:E1077"},
    {"phrase":"e1078","reason":"placeholder_name","source":"name:E1078"},
    {"phrase":"e1079","reason":"placeholder_name","source":"name:E1079"},
    {"phrase":"e1080","reason":"placeholder_name","source":"name:E1080"},
    {"phrase":"e1081","reason":"placeholder_name","source":"name:E1081"},
    {"phrase":"e1082","reason":"placeholder_name","source":"name:E1082"},
    {"phrase":"e1083","reason":"placeholder_name","source":"name:E1083"},
    {"phrase":"e1084","reason":"placeholder_name","source":"name:E1084"},
    {"phrase":"e1085","reason":"placeholder_name","source":"name:E1085"},
    {"phrase":"e1086","reason":"placeholder_name","source":"name:E1086"},
    {"phrase":"e1087","reason":"placeholder_name","source":"name:E1087"},
    {"phrase":"e1088","reason":"placeholder_name","source":"name:E1088"},
    {"phrase":"e1089","reason":"placeholder_name","source":"name:E1089"},
    {"phrase":"e1090","reason":"placeholder_name","source":"name:E1090"},
    {"phrase":"e1091","reason":"placeholder_name","source":"name:E1091"},
    {"phrase":"e1092","reason":"placeholder_name","source":"name:E1092"},
    {"phrase":"e1093","reason":"placeholder_name","source":"name:E1093"},
    {"phrase":"e1094","reason":"placeholder_name","source":"name:E1094"},
    {"phrase":"e1095","reason":"placeholder_name","source":"name:E1095"},
    {"phrase":"e1096","reason":"placeholder_name","source":"name:E1096"},
    {"phrase":"e1097","reason":"placeholder_name","source":"name:E1097"},
    {"phrase":"e1098","reason":"placeholder_name","source":"name:E1098"},
    {"phrase":"e1099","reason":"placeholder_name","source":"name:E1099"},
    {"phrase":"e1100","reason":"placeholder_name","source":"name:E1100"},
    {"phrase":"e1101","reason":"placeholder_name","source":"name:E1101"},
    {"phrase":"e1102","reason":"placeholder_name","source":"name:E1102"},
    {"phrase":"e1103","reason":"placeholder_name","source":"name:E1103"},
    {"phrase":"e1104","reason":"placeholder_name","source":"name:E1104"},
    {"phrase":"e1105","reason":"placeholder_name","source":"name:E1105"},
    {"phrase":"e1106","reason":"placeholder_name","source":"name:E1106"},
    {"phrase":"e1107","reason":"placeholder_name","source":"name:E1107"},
    {"phrase":"e1108","reason":"placeholder_name","source":"name:E1108"},
    {"phrase":"e1109","reason":"placeholder_name","source":"name:E1109"},
    {"phrase":"e1110","reason":"placeholder_name","source":"name:E1110"},
    {"phrase":"e1111","reason":"placeholder_name","source":"name:E1111"},
    {"phrase":"e1112","reason":"placeholder_name","source":"name:E1112"},
    {"phrase":"e1113","reason":"placeholder_name","source":"name:E1113"},
    {"phrase":"e1114","reason":"placeholder_name","source":"name:E1114"},
    {"phrase":"e1115","reason":"placeholder_name","source":"name:E1115"},
    {"phrase":"e1116","reason":"placeholder_name","source":"name:E1116"},
    {"phrase":"e1117","reason":"placeholder_name","source":"name:E1117"},
    {"phrase":"e1118","reason":"placeholder_name","source":"name:E1118"},
    {"phrase":"e1119","reason":"placeholder_name","source":"name:E1119"},
    {"phrase":"e1120","reason":"placeholder_name","source":"name:E1120"},
    {"phrase":"e1121","reason":"placeholder_name","source":"name:E1121"},
    {"phrase":"e1122","reason":"placeholder_name","source":"name:E1122"},
    {"phrase":"e1123","reason":"placeholder_name","source":"name:E1123"},
    {"phrase":"e1124","reason":"placeholder_name","source":"name:E1124"},
    {"phrase":"e1125","reason":"placeholder_name","source":"name:E1125"},
    {"phrase":"e1126","reason":"placeholder_name","source":"name:E1126"},
    {"phrase":"e1127","reason":"placeholder_name","source":"name:E1127"},
    {"phrase":"e1128","reason":"placeholder_name","source":"name:E1128"},
    {"phrase":"e1129","reason":"placeholder_name","source":"name:E1129"},
    {"phrase":"e1130","reason":"placeholder_name","source":"name:E1130"},
    {"phrase":"e1131","reason":"placeholder_name","source":"name:E1131"},
    {"phrase":"e1132","reason":"placeholder_name","source":"name:E1132"},
    {"phrase":"e1133","reason":"placeholder_name","source":"name:E1133"},
    {"phrase":"e1134","reason":"placeholder_name","source":"name:E1134"},
    {"phrase":"e1135","reason":"placeholder_name","source":"name:E1135"},
    {"phrase":"e1136","reason":"placeholder_name","source":"name:E1136"},
    {"phrase":"e1137","reason":"placeholder_name","source":"name:E1137"},
    {"phrase":"e1138","reason":"placeholder_name","source":"name:E1138"},
    {"phrase":"e1139","reason":"placeholder_name","source":"name:E1139"},
    {"phrase":"e1140","reason":"placeholder_name","source":"name:E1140"},
    {"phrase":"e1141","reason":"placeholder_name","source":"name:E1141"},
    {"phrase":"e1142","reason":"placeholder_name","source":"name:E1142"},
    {"phrase":"e1143","reason":"placeholder_name","source":"name:E1143"},
    {"phrase":"e1144","reason":"placeholder_name","source":"name:E1144"},
    {"phrase":"e1145","reason":"placeholder_name","source":"name:E1145"},
    {"phrase":"e1146","reason":"placeholder_name","source":"name:E1146"},
    {"phrase":"e1147","reason":"placeholder_name","source":"name:E1147"},
    {"phrase":"e1148","reason":"placeholder_name","source":"name:E1148"},
    {"phrase":"e1149","reason":"placeholder_name","source":"name:E1149"},
    {"phrase":"e1150","reason":"placeholder_name","source":"name:E1150"},
    {"phrase":"e1151","reason":"placeholder_name","source":"name:E1151"},
    {"phrase":"e1152","reason":"placeholder_name","source":"name:E1152"},
    {"phrase":"e1153","reason":"placeholder_name","source":"name:E1153"},
    {"phrase":"e1154","reason":"placeholder_name","source":"name:E1154"},
    {"phrase":"e1155","reason":"placeholder_name","source":"name:E1155"},
    {"phrase":"e1156","reason":"placeholder_name","source":"name:E1156"},
    {"phrase":"e1157","reason":"placeholder_name","source":"name:E1157"},
    {"phrase":"e1158","reason":"placeholder_name","source":"name:E1158"},
    {"phrase":"e1159","reason":"placeholder_name","source":"name:E1159"},
    {"phrase":"e1160","reason":"placeholder_name","source":"name:E1160"},
    {"phrase":"e1161","reason":"placeholder_name","source":"name:E1161"},
    {"phrase":"e1162","reason":"placeholder_name","source":"name:E1162"},
    {"phrase":"e1163","reason":"placeholder_name","source":"name:E1163"},
    {"phrase":"e1164","reason":"placeholder_name","source":"name:E1164"},
    {"phrase":"e1165","reason":"placeholder_name","source":"name:E1165"},
    {"phrase":"e1166","reason":"placeholder_name","source":"name:E1166"},
    {"phrase":"e1167","reason":"placeholder_name","source":"name:E1167"},
    {"phrase":"e1168","reason":"placeholder_name","source":"name:E1168"},
    {"phrase":"e1169","reason":"placeholder_name","source":"name:E1169"},
    {"phrase":"e1170","reason":"placeholder_name","source":"name:E1170"},
    {"phrase":"e1171","reason":"placeholder_name","source":"name:E1171"},
    {"phrase":"e1172","reason":"placeholder_name","source":"name:E1172"},
    {"phrase":"e1173","reason":"placeholder_name","source":"name:E1173"},
    {"phrase":"e1174","reason":"placeholder_name","source":"name:E1174"},
    {"phrase":"e1175","reason":"placeholder_name","source":"name:E1175"},
    {"phrase":"e1176","reason":"placeholder_name","source":"name:E1176"},
    {"phrase":"e1177","reason":"placeholder_name","source":"name:E1177"},
    {"phrase":"e1178","reason":"placeholder_name","source":"name:E1178"},
    {"phrase":"e1179","reason":"placeholder_name","source":"name:E1179"},
    {"phrase":"e1180","reason":"placeholder_name","source":"name:E1180"},
    {"phrase":"e1181","reason":"placeholder_name","source":"name:E1181"},
    {"phrase":"e1182","reason":"placeholder_name","source":"name:E1182"},
    {"phrase":"e1183","reason":"placeholder_name","source":"name:E1183"},
    {"phrase":"e1184","reason":"placeholder_name","source":"name:E1184"},
    {"phrase":"e1185","reason":"placeholder_name","source":"name:E1185"},
    {"phrase":"e1186","reason":"placeholder_name","source":"name:E1186"},
    {"phrase":"e1187","reason":"placeholder_name","source":"name:E1187"},
    {"phrase":"e1188","reason":"placeholder_name","source":"name:E1188"},
    {"phrase":"e1189","reason":"placeholder_name","source":"name:E1189"},
    {"phrase":"e1190","reason":"placeholder_name","source":"name:E1190"},
    {"phrase":"e1191","reason":"placeholder_name","source":"name:E1191"},
    {"phrase":"e1192","reason":"placeholder_name","source":"name:E1192"},
    {"phrase":"e1193","reason":"placeholder_name","source":"name:E1193"},
    {"phrase":"e1194","reason":"placeholder_name","source":"name:E1194"},
    {"phrase":"e1195","reason":"placeholder_name","source":"name:E1195"},
    {"phrase":"e1196","reason":"placeholder_name","source":"name:E1196"},
    {"phrase":"e1197","reason":"placeholder_name","source":"name:E1197"},
    {"phrase":"e1198","reason":"placeholder_name","source":"name:E1198"},
    {"phrase":"e1199","reason":"placeholder_name","source":"name:E1199"},
    {"phrase":"e1205","reason":"placeholder_name","source":"name:E1205"},
    {"phrase":"e1206","reason":"placeholder_name","source":"name:E1206"},
    {"phrase":"e1207","reason":"placeholder_name","source":"name:E1207"},
    {"phrase":"e1208","reason":"placeholder_name","source":"name:E1208"},
    {"phrase":"e1209","reason":"placeholder_name","source":"name:E1209"},
    {"phrase":"e1210","reason":"placeholder_name","source":"name:E1210"},
    {"phrase":"e1211","reason":"placeholder_name","source":"name:E1211"},
    {"phrase":"e1212","reason":"placeholder_name","source":"name:E1212"},
    {"phrase":"e1213","reason":"placeholder_name","source":"name:E1213"},
    {"phrase":"e1214","reason":"placeholder_name","source":"name:E1214"},
    {"phrase":"e1215","reason":"placeholder_name","source":"name:E1215"},
    {"phrase":"e1216","reason":"placeholder_name","source":"name:E1216"},
    {"phrase":"e1217","reason":"placeholder_name","source":"name:E1217"},
    {"phrase":"e1218","reason":"placeholder_name","source":"name:E1218"},
    {"phrase":"e1219","reason":"placeholder_name","source":"name:E1219"},
    {"phrase":"e1220","reason":"placeholder_name","source":"name:E1220"},
    {"phrase":"e1221","reason":"placeholder_name","source":"name:E1221"},
    {"phrase":"e1222","reason":"placeholder_name","source":"name:E1222"},
    {"phrase":"e1223","reason":"placeholder_name","source":"name:E1223"},
    {"phrase":"e1224","reason":"placeholder_name","source":"name:E1224"},
    {"phrase":"e1225","reason":"placeholder_name","source":"name:E1225"},
    {"phrase":"e1226","reason":"placeholder_name","source":"name:E1226"},
    {"phrase":"e1227","reason":"placeholder_name","source":"name:E1227"},
    {"phrase":"e1228","reason":"placeholder_name","source":"name:E1228"},
    {"phrase":"e1229","reason":"placeholder_name","source":"name:E1229"},
    {"phrase":"e1230","reason":"placeholder_name","source":"name:E1230"},
    {"phrase":"e1231","reason":"placeholder_name","source":"name:E1231"},
    {"phrase":"e1232","reason":"placeholder_name","source":"name:E1232"},
    {"phrase":"e1233","reason":"placeholder_name","source":"name:E1233"},
    {"phrase":"e1234","reason":"placeholder_name","source":"name:E1234"},
    {"phrase":"e1235","reason":"placeholder_name","source":"name:E1235"},
    {"phrase":"e1236","reason":"placeholder_name","source":"name:E1236"},
    {"phrase":"e1237","reason":"placeholder_name","source":"name:E1237"},
    {"phrase":"e1238","reason":"placeholder_name","source":"name:E1238"},
    {"phrase":"e1239","reason":"placeholder_name","source":"name:E1239"},
    {"phrase":"e1240","reason":"placeholder_name","source":"name:E1240"},
    {"phrase":"e1241","reason":"placeholder_name","source":"name:E1241"},
    {"phrase":"e1242","reason":"placeholder_name","source":"name:E1242"},
    {"phrase":"e1243","reason":"placeholder_name","source":"name:E1243"},
    {"phrase":"e1244","reason":"placeholder_name","source":"name:E1244"},
    {"phrase":"e1245","reason":"placeholder_name","source":"name:E1245"},
    {"phrase":"e1246","reason":"placeholder_name","source":"name:E1246"},
    {"phrase":"e1247","reason":"placeholder_name","source":"name:E1247"},
    {"phrase":"e1248","reason":"placeholder_name","source":"name:E1248"},
    {"phrase":"e1249","reason":"placeholder_name","source":"name:E1249"},
    {"phrase":"e1250","reason":"placeholder_name","source":"name:E1250"},
    {"phrase":"e1251","reason":"placeholder_name","source":"name:E1251"},
    {"phrase":"e1252","reason":"placeholder_name","source":"name:E1252"},
    {"phrase":"e1253","reason":"placeholder_name","source":"name:E1253"},
    {"phrase":"e1254","reason":"placeholder_name","source":"name:E1254"},
    {"phrase":"e1255","reason":"placeholder_name","source":"name:E1255"},
    {"phrase":"e1256","reason":"placeholder_name","source":"name:E1256"},
    {"phrase":"e1257","reason":"placeholder_name","source":"name:E1257"},
    {"phrase":"e1258","reason":"placeholder_name","source":"name:E1258"},
    {"phrase":"e1259","reason":"placeholder_name","source":"name:E1259"},
    {"phrase":"e1260","reason":"placeholder_name","source":"name:E1260"},
    {"phrase":"e1261","reason":"placeholder_name","source":"name:E1261"},
    {"phrase":"e1262","reason":"placeholder_name","source":"name:E1262"},
    {"phrase":"e1263","reason":"placeholder_name","source":"name:E1263"},
    {"phrase":"e1264","reason":"placeholder_name","source":"name:E1264"},
    {"phrase":"e1265","reason":"placeholder_name","source":"name:E1265"},
    {"phrase":"e1266","reason":"placeholder_name","source":"name:E1266"},
    {"phrase":"e1267","reason":"placeholder_name","source":"name:E1267"},
    {"phrase":"e1268","reason":"placeholder_name","source":"name:E1268"},
    {"phrase":"e1269","reason":"placeholder_name","source":"name:E1269"},
    {"phrase":"e1270","reason":"placeholder_name","source":"name:E1270"},
    {"phrase":"e1271","reason":"placeholder_name","source":"name:E1271"},
    {"phrase":"e1272","reason":"placeholder_name","source":"name:E1272"},
    {"phrase":"e1273","reason":"placeholder_name","source":"name:E1273"},
    {"phrase":"e1274","reason":"placeholder_name","source":"name:E1274"},
    {"phrase":"e1275","reason":"placeholder_name","source":"name:E1275"},
    {"phrase":"e1276","reason":"placeholder_name","source":"name:E1276"},
    {"phrase":"e1277","reason":"placeholder_name","source":"name:E1277"},
    {"phrase":"e1278","reason":"placeholder_name","source":"name:E1278"},
    {"phrase":"e1279","reason":"placeholder_name","source":"name:E1279"},
    {"phrase":"e1280","reason":"placeholder_name","source":"name:E1280"},
    {"phrase":"e1281","reason":"placeholder_name","source":"name:E1281"},
    {"phrase":"e1282","reason":"placeholder_name","source":"name:E1282"},
    {"phrase":"e1283","reason":"placeholder_name","source":"name:E1283"},
    {"phrase":"e1284","reason":"placeholder_name","source":"name:E1284"},
    {"phrase":"e1285","reason":"placeholder_name","source":"name:E1285"},
    {"phrase":"e1286","reason":"placeholder_name","source":"name:E1286"},
    {"phrase":"e1287","reason":"placeholder_name","source":"name:E1287"},
    {"phrase":"e1288","reason":"placeholder_name","source":"name:E1288"},
    {"phrase":"e1289","reason":"placeholder_name","source":"name:E1289"},
    {"phrase":"e1290","reason":"placeholder_name","source":"name:E1290"},
    {"phrase":"e1291","reason":"placeholder_name","source":"name:E1291"},
    {"phrase":"e1292","reason":"placeholder_name","source":"name:E1292"},
    {"phrase":"e1293","reason":"placeholder_name","source":"name:E1293"},
    {"phrase":"e1294","reason":"placeholder_name","source":"name:E1294"},
    {"phrase":"e1295","reason":"placeholder_name","source":"name:E1295"},
    {"phrase":"e1296","reason":"placeholder_name","source":"name:E1296"},
    {"phrase":"e1297","reason":"placeholder_name","source":"name:E1297"},
    {"phrase":"e1298","reason":"placeholder_name","source":"name:E1298"},
    {"phrase":"e1299","reason":"placeholder_name","source":"name:E1299"},
    {"phrase":"e1300","reason":"placeholder_name","source":"name:E1300"},
    {"phrase":"e1301","reason":"placeholder_name","source":"name:E1301"},
    {"phrase":"e1302","reason":"placeholder_name","source":"name:E1302"},
    {"phrase":"e1303","reason":"placeholder_name","source":"name:E1303"},
    {"phrase":"e1304","reason":"placeholder_name","source":"name:E1304"},
    {"phrase":"e1305","reason":"placeholder_name","source":"name:E1305"},
    {"phrase":"e1306","reason":"placeholder_name","source":"name:E1306"},
    {"phrase":"e1307","reason":"placeholder_name","source":"name:E1307"},
    {"phrase":"e1308","reason":"placeholder_name","source":"name:E1308"},
    {"phrase":"e1309","reason":"placeholder_name","source":"name:E1309"},
    {"phrase":"e1310","reason":"placeholder_name","source":"name:E1310"},
    {"phrase":"e1311","reason":"placeholder_name","source":"name:E1311"},
    {"phrase":"e1312","reason":"placeholder_name","source":"name:E1312"},
    {"phrase":"e1313","reason":"placeholder_name","source":"name:E1313"},
    {"phrase":"e1314","reason":"placeholder_name","source":"name:E1314"},
    {"phrase":"e1315","reason":"placeholder_name","source":"name:E1315"},
    {"phrase":"e1316","reason":"placeholder_name","source":"name:E1316"},
    {"phrase":"e1317","reason":"placeholder_name","source":"name:E1317"},
    {"phrase":"e1318","reason":"placeholder_name","source":"name:E1318"},
    {"phrase":"e1319","reason":"placeholder_name","source":"name:E1319"},
    {"phrase":"e1320","reason":"placeholder_name","source":"name:E1320"},
    {"phrase":"e1321","reason":"placeholder_name","source":"name:E1321"},
    {"phrase":"e1322","reason":"placeholder_name","source":"name:E1322"},
    {"phrase":"e1323","reason":"placeholder_name","source":"name:E1323"},
    {"phrase":"e1324","reason":"placeholder_name","source":"name:E1324"},
    {"phrase":"e1325","reason":"placeholder_name","source":"name:E1325"},
    {"phrase":"e1326","reason":"placeholder_name","source":"name:E1326"},
    {"phrase":"e1327","reason":"placeholder_name","source":"name:E1327"},
    {"phrase":"e1328","reason":"placeholder_name","source":"name:E1328"},
    {"phrase":"e1329","reason":"placeholder_name","source":"name:E1329"},
    {"phrase":"e1330","reason":"placeholder_name","source":"name:E1330"},
    {"phrase":"e1331","reason":"placeholder_name","source":"name:E1331"},
    {"phrase":"e1332","reason":"placeholder_name","source":"name:E1332"},
    {"phrase":"e1333","reason":"placeholder_name","source":"name:E1333"},
    {"phrase":"e1334","reason":"placeholder_name","source":"name:E1334"},
    {"phrase":"e1335","reason":"placeholder_name","source":"name:E1335"},
    {"phrase":"e1336","reason":"placeholder_name","source":"name:E1336"},
    {"phrase":"e1337","reason":"placeholder_name","source":"name:E1337"},
    {"phrase":"e1338","reason":"placeholder_name","source":"name:E1338"},
    {"phrase":"e1339","reason":"placeholder_name","source":"name:E1339"},
    {"phrase":"e1340","reason":"placeholder_name","source":"name:E1340"},
    {"phrase":"e1341","reason":"placeholder_name","source":"name:E1341"},
    {"phrase":"e1342","reason":"placeholder_name","source":"name:E1342"},
    {"phrase":"e1343","reason":"placeholder_name","source":"name:E1343"},
    {"phrase":"e1344","reason":"placeholder_name","source":"name:E1344"},
    {"phrase":"e1345","reason":"placeholder_name","source":"name:E1345"},
    {"phrase":"e1346","reason":"placeholder_name","source":"name:E1346"},
    {"phrase":"e1347","reason":"placeholder_name","source":"name:E1347"},
    {"phrase":"e1348","reason":"placeholder_name","source":"name:E1348"},
    {"phrase":"e1349","reason":"placeholder_name","source":"name:E1349"},
    {"phrase":"e1350","reason":"placeholder_name","source":"name:E1350"},
    {"phrase":"e1351","reason":"placeholder_name","source":"name:E1351"},
    {"phrase":"e1352","reason":"placeholder_name","source":"name:E1352"},
    {"phrase":"e1353","reason":"placeholder_name","source":"name:E1353"},
    {"phrase":"e1354","reason":"placeholder_name","source":"name:E1354"},
    {"phrase":"e1355","reason":"placeholder_name","source":"name:E1355"},
    {"phrase":"e1356","reason":"placeholder_name","source":"name:E1356"},
    {"phrase":"e1357","reason":"placeholder_name","source":"name:E1357"},
    {"phrase":"e1358","reason":"placeholder_name","source":"name:E1358"},
    {"phrase":"e1359","reason":"placeholder_name","source":"name:E1359"},
    {"phrase":"e1360","reason":"placeholder_name","source":"name:E1360"},
    {"phrase":"e1361","reason":"placeholder_name","source":"name:E1361"},
    {"phrase":"e1362","reason":"placeholder_name","source":"name:E1362"},
    {"phrase":"e1363","reason":"placeholder_name","source":"name:E1363"},
    {"phrase":"e1364","reason":"placeholder_name","source":"name:E1364"},
    {"phrase":"e1365","reason":"placeholder_name","source":"name:E1365"},
    {"phrase":"e1366","reason":"placeholder_name","source":"name:E1366"},
    {"phrase":"e1367","reason":"placeholder_name","source":"name:E1367"},
    {"phrase":"e1368","reason":"placeholder_name","source":"name:E1368"},
    {"phrase":"e1369","reason":"placeholder_name","source":"name:E1369"},
    {"phrase":"e1370","reason":"placeholder_name","source":"name:E1370"},
    {"phrase":"e1371","reason":"placeholder_name","source":"name:E1371"},
    {"phrase":"e1372","reason":"placeholder_name","source":"name:E1372"},
    {"phrase":"e1373","reason":"placeholder_name","source":"name:E1373"},
    {"phrase":"e1374","reason":"placeholder_name","source":"name:E1374"},
    {"phrase":"e1375","reason":"placeholder_name","source":"name:E1375"},
    {"phrase":"e1376","reason":"placeholder_name","source":"name:E1376"},
    {"phrase":"e1377","reason":"placeholder_name","source":"name:E1377"},
    {"phrase":"e1378","reason":"placeholder_name","source":"name:E1378"},
    {"phrase":"e1379","reason":"placeholder_name","source":"name:E1379"},
    {"phrase":"e1380","reason":"placeholder_name","source":"name:E1380"},
    {"phrase":"e1381","reason":"placeholder_name","source":"name:E1381"},
    {"phrase":"e1382","reason":"placeholder_name","source":"name:E1382"},
    {"phrase":"e1383","reason":"placeholder_name","source":"name:E1383"},
    {"phrase":"e1384","reason":"placeholder_name","source":"name:E1384"},
    {"phrase":"e1385","reason":"placeholder_name","source":"name:E1385"},
    {"phrase":"e1386","reason":"placeholder_name","source":"name:E1386"},
    {"phrase":"e1387","reason":"placeholder_name","source":"name:E1387"},
    {"phrase":"e1388","reason":"placeholder_name","source":"name:E1388"},
    {"phrase":"e1389","reason":"placeholder_name","source":"name:E1389"},
    {"phrase":"e1390","reason":"placeholder_name","source":"name:E1390"},
    {"phrase":"e1391","reason":"placeholder_name","source":"name:E1391"},
    {"phrase":"e1392","reason":"placeholder_name","source":"name:E1392"},
    {"phrase":"e1393","reason":"placeholder_name","source":"name:E1393"},
    {"phrase":"e1394","reason":"placeholder_name","source":"name:E1394"},
    {"phrase":"e1395","reason":"placeholder_name","source":"name:E1395"},
    {"phrase":"e1396","reason":"placeholder_name","source":"name:E1396"},
    {"phrase":"e1397","reason":"placeholder_name","source":"name:E1397"},
    {"phrase":"e1398","reason":"placeholder_name","source":"name:E1398"},
    {"phrase":"e1399","reason":"placeholder_name","source":"name:E1399"},
    {"phrase":"e1406","reason":"placeholder_name","source":"name:E1406"},
    {"phrase":"e1407","reason":"placeholder_name","source":"name:E1407"},
    {"phrase":"e1408","reason":"placeholder_name","source":"name:E1408"},
    {"phrase":"e1409","reason":"placeholder_name","source":"name:E1409"},
    {"phrase":"e1411","reason":"placeholder_name","source":"name:E1411"},
    {"phrase":"e1415","reason":"placeholder_name","source":"name:E1415"},
    {"phrase":"e1416","reason":"placeholder_name","source":"name:E1416"},
    {"phrase":"e1417","reason":"placeholder_name","source":"name:E1417"},
    {"phrase":"e1418","reason":"placeholder_name","source":"name:E1418"},
    {"phrase":"e1419","reason":"placeholder_name","source":"name:E1419"},
    {"phrase":"e1421","reason":"placeholder_name","source":"name:E1421"},
    {"phrase":"e1423","reason":"placeholder_name","source":"name:E1423"},
    {"phrase":"e1424","reason":"placeholder_name","source":"name:E1424"},
    {"phrase":"e1425","reason":"placeholder_name","source":"name:E1425"},
    {"phrase":"e1426","reason":"placeholder_name","source":"name:E1426"},
    {"phrase":"e1427","reason":"placeholder_name","source":"name:E1427"},
    {"phrase":"e1428","reason":"placeholder_name","source":"name:E1428"},
    {"phrase":"e1429","reason":"placeholder_name","source":"name:E1429"},
    {"phrase":"e1430","reason":"placeholder_name","source":"name:E1430"},
    {"phrase":"e1431","reason":"placeholder_name","source":"name:E1431"},
    {"phrase":"e1432","reason":"placeholder_name","source":"name:E1432"},
    {"phrase":"e1433","reason":"placeholder_name","source":"name:E1433"},
    {"phrase":"e1434","reason":"placeholder_name","source":"name:E1434"},
    {"phrase":"e1435","reason":"placeholder_name","source":"name:E1435"},
    {"phrase":"e1436","reason":"placeholder_name","source":"name:E1436"},
    {"phrase":"e1437","reason":"placeholder_name","source":"name:E1437"},
    {"phrase":"e1438","reason":"placeholder_name","source":"name:E1438"},
    {"phrase":"e1439","reason":"placeholder_name","source":"name:E1439"},
    {"phrase":"e1441","reason":"placeholder_name","source":"name:E1441"},
    {"phrase":"e1443","reason":"placeholder_name","source":"name:E1443"},
    {"phrase":"e1444","reason":"placeholder_name","source":"name:E1444"},
    {"phrase":"e1445","reason":"placeholder_name","source":"name:E1445"},
    {"phrase":"e1446","reason":"placeholder_name","source":"name:E1446"},
    {"phrase":"e1447","reason":"placeholder_name","source":"name:E1447"},
    {"phrase":"e1448","reason":"placeholder_name","source":"name:E1448"},
    {"phrase":"e1449","reason":"placeholder_name","source":"name:E1449"},
    {"phrase":"e1453","reason":"placeholder_name","source":"name:E1453"},
    {"phrase":"e1454","reason":"placeholder_name","source":"name:E1454"},
    {"phrase":"e1455","reason":"placeholder_name","source":"name:E1455"},
    {"phrase":"e1456","reason":"placeholder_name","source":"name:E1456"},
    {"phrase":"e1457","reason":"placeholder_name","source":"name:E1457"},
    {"phrase":"e1458","reason":"placeholder_name","source":"name:E1458"},
    {"phrase":"e1459","reason":"placeholder_name","source":"name:E1459"},
    {"phrase":"e1460","reason":"placeholder_name","source":"name:E1460"},
    {"phrase":"e1461","reason":"placeholder_name","source":"name:E1461"},
    {"phrase":"e1462","reason":"placeholder_name","source":"name:E1462"},
    {"phrase":"e1463","reason":"placeholder_name","source":"name:E1463"},
    {"phrase":"e1464","reason":"placeholder_name","source":"name:E1464"},
    {"phrase":"e1465","reason":"placeholder_name","source":"name:E1465"},
    {"phrase":"e1466","reason":"placeholder_name","source":"name:E1466"},
    {"phrase":"e1467","reason":"placeholder_name","source":"name:E1467"},
    {"phrase":"e1468","reason":"placeholder_name","source":"name:E1468"},
    {"phrase":"e1469","reason":"placeholder_name","source":"name:E1469"},
    {"phrase":"e1470","reason":"placeholder_name","source":"name:E1470"},
    {"phrase":"e1471","reason":"placeholder_name","source":"name:E1471"},
    {"phrase":"e1472","reason":"placeholder_name","source":"name:E1472"},
    {"phrase":"e1473","reason":"placeholder_name","source":"name:E1473"},
    {"phrase":"e1474","reason":"placeholder_name","source":"name:E1474"},
    {"phrase":"e1475","reason":"placeholder_name","source":"name:E1475"},
    {"phrase":"e1476","reason":"placeholder_name","source":"name:E1476"},
    {"phrase":"e1477","reason":"placeholder_name","source":"name:E1477"},
    {"phrase":"e1478","reason":"placeholder_name","source":"name:E1478"},
    {"phrase":"e1479","reason":"placeholder_name","source":"name:E1479"},
    {"phrase":"e1480","reason":"placeholder_name","source":"name:E1480"},
    {"phrase":"e1481","reason":"placeholder_name","source":"name:E1481"},
    {"phrase":"e1482","reason":"placeholder_name","source":"name:E1482"},
    {"phrase":"e1483","reason":"placeholder_name","source":"name:E1483"},
    {"phrase":"e1484","reason":"placeholder_name","source":"name:E1484"},
    {"phrase":"e1485","reason":"placeholder_name","source":"name:E1485"},
    {"phrase":"e1486","reason":"placeholder_name","source":"name:E1486"},
    {"phrase":"e1487","reason":"placeholder_name","source":"name:E1487"},
    {"phrase":"e1488","reason":"placeholder_name","source":"name:E1488"},
    {"phrase":"e1489","reason":"placeholder_name","source":"name:E1489"},
    {"phrase":"e1490","reason":"placeholder_name","source":"name:E1490"},
    {"phrase":"e1491","reason":"placeholder_name","source":"name:E1491"},
    {"phrase":"e1492","reason":"placeholder_name","source":"name:E1492"},
    {"phrase":"e1493","reason":"placeholder_name","source":"name:E1493"},
    {"phrase":"e1494","reason":"placeholder_name","source":"name:E1494"},
    {"phrase":"e1495","reason":"placeholder_name","source":"name:E1495"},
    {"phrase":"e1496","reason":"placeholder_name","source":"name:E1496"},
    {"phrase":"e1497","reason":"placeholder_name","source":"name:E1497"},
    {"phrase":"e1498","reason":"placeholder_name","source":"name:E1498"},
    {"phrase":"e1499","reason":"placeholder_name","source":"name:E1499"},
    {"phrase":"e1500","reason":"placeholder_name","source":"name:E1500"},
    {"phrase":"e1501","reason":"placeholder_name","source":"name:E1501"},
    {"phrase":"e1502","reason":"placeholder_name","source":"name:E1502"},
    {"phrase":"e1503","reason":"placeholder_name","source":"name:E1503"},
    {"phrase":"e1504","reason":"placeholder_name","source":"name:E1504"},
    {"phrase":"e1506","reason":"placeholder_name","source":"name:E1506"},
    {"phrase":"e1507","reason":"placeholder_name","source":"name:E1507"},
    {"phrase":"e1508","reason":"placeholder_name","source":"name:E1508"},
    {"phrase":"e1509","reason":"placeholder_name","source":"name:E1509"},
    {"phrase":"e1510","reason":"placeholder_name","source":"name:E1510"},
    {"phrase":"e1511","reason":"placeholder_name","source":"name:E1511"},
    {"phrase":"e1512","reason":"placeholder_name","source":"name:E1512"},
    {"phrase":"e1513","reason":"placeholder_name","source":"name:E1513"},
    {"phrase":"e1514","reason":"placeholder_name","source":"name:E1514"},
    {"phrase":"e1515","reason":"placeholder_name","source":"name:E1515"},
    {"phrase":"e1516","reason":"placeholder_name","source":"name:E1516"},
    {"phrase":"e1517","reason":"placeholder_name","source":"name:E1517"},
    {"phrase":"e1519","reason":"placeholder_name","source":"name:E1519"},
    {"phrase":"e286","reason":"placeholder_name","source":"name:E286"},
    {"phrase":"e287","reason":"placeholder_name","source":"name:E287"},
    {"phrase":"e288","reason":"placeholder_name","source":"name:E288"},
    {"phrase":"e289","reason":"placeholder_name","source":"name:E289"},
    {"phrase":"e291","reason":"placeholder_name","source":"name:E291"},
    {"phrase":"e292","reason":"placeholder_name","source":"name:E292"},
    {"phrase":"e293","reason":"placeholder_name","source":"name:E293"},
    {"phrase":"e294","reason":"placeholder_name","source":"name:E294"},
    {"phrase":"e295","reason":"placeholder_name","source":"name:E295"},
    {"phrase":"e298","reason":"placeholder_name","source":"name:E298"},
    {"phrase":"e299","reason":"placeholder_name","source":"name:E299"},
    {"phrase":"e305","reason":"placeholder_name","source":"name:E305"},
    {"phrase":"e423","reason":"placeholder_name","source":"name:E423"},
    {"phrase":"e424","reason":"placeholder_name","source":"name:E424"},
    {"phrase":"e462","reason":"placeholder_name","source":"name:E462"},
    {"phrase":"e467","reason":"placeholder_name","source":"name:E467"},
    {"phrase":"e502","reason":"placeholder_name","source":"name:E502"},
    {"phrase":"e505","reason":"placeholder_name","source":"name:E505"},
    {"phrase":"e506","reason":"placeholder_name","source":"name:E506"},
    {"phrase":"e518","reason":"placeholder_name","source":"name:E518"},
    {"phrase":"e519","reason":"placeholder_name","source":"name:E519"},
    {"phrase":"e531","reason":"placeholder_name","source":"name:E531"},
    {"phrase":"e532","reason":"placeholder_name","source":"name:E532"},
    {"phrase":"e533","reason":"placeholder_name","source":"name:E533"},
    {"phrase":"e534","reason":"placeholder_name","source":"name:E534"},
    {"phrase":"e537","reason":"placeholder_name","source":"name:E537"},
    {"phrase":"e539","reason":"placeholder_name","source":"name:E539"},
    {"phrase":"e543","reason":"placeholder_name","source":"name:E543"},
    {"phrase":"e546","reason":"placeholder_name","source":"name:E546"},
    {"phrase":"e547","reason":"placeholder_name","source":"name:E547"},
    {"phrase":"e548","reason":"placeholder_name","source":"name:E548"},
    {"phrase":"e549","reason":"placeholder_name","source":"name:E549"},
    {"phrase":"e557","reason":"placeholder_name","source":"name:E557"},
    {"phrase":"e560","reason":"placeholder_name","source":"name:E560"},
    {"phrase":"e561","reason":"placeholder_name","source":"name:E561"},
    {"phrase":"e562","reason":"placeholder_name","source":"name:E562"},
    {"phrase":"e563","reason":"placeholder_name","source":"name:E563"},
    {"phrase":"e564","reason":"placeholder_name","source":"name:E564"},
    {"phrase":"e565","reason":"placeholder_name","source":"name:E565"},
    {"phrase":"e566","reason":"placeholder_name","source":"name:E566"},
    {"phrase":"e567","reason":"placeholder_name","source":"name:E567"},
    {"phrase":"e568","reason":"placeholder_name","source":"name:E568"},
    {"phrase":"e569","reason":"placeholder_name","source":"name:E569"},
    {"phrase":"e571","reason":"placeholder_name","source":"name:E571"},
    {"phrase":"e572","reason":"placeholder_name","source":"name:E572"},
    {"phrase":"e573","reason":"placeholder_name","source":"name:E573"},
    {"phrase":"e580","reason":"placeholder_name","source":"name:E580"},
    {"phrase":"e581","reason":"placeholder_name","source":"name:E581"},
    {"phrase":"e582","reason":"placeholder_name","source":"name:E582"},
    {"phrase":"e583","reason":"placeholder_name","source":"name:E583"},
    {"phrase":"e584","reason":"placeholder_name","source":"name:E584"},
    {"phrase":"e586","reason":"placeholder_name","source":"name:E586"},
    {"phrase":"e587","reason":"placeholder_name","source":"name:E587"},
    {"phrase":"e588","reason":"placeholder_name","source":"name:E588"},
    {"phrase":"e589","reason":"placeholder_name","source":"name:E589"},
    {"phrase":"e590","reason":"placeholder_name","source":"name:E590"},
    {"phrase":"e591","reason":"placeholder_name","source":"name:E591"},
    {"phrase":"e592","reason":"placeholder_name","source":"name:E592"},
    {"phrase":"e593","reason":"placeholder_name","source":"name:E593"},
    {"phrase":"e594","reason":"placeholder_name","source":"name:E594"},
    {"phrase":"e595","reason":"placeholder_name","source":"name:E595"},
    {"phrase":"e596","reason":"placeholder_name","source":"name:E596"},
    {"phrase":"e597","reason":"placeholder_name","source":"name:E597"},
    {"phrase":"e598","reason":"placeholder_name","source":"name:E598"},
    {"phrase":"e599","reason":"placeholder_name","source":"name:E599"},
    {"phrase":"e600","reason":"placeholder_name","source":"name:E600"},
    {"phrase":"e601","reason":"placeholder_name","source":"name:E601"},
    {"phrase":"e602","reason":"placeholder_name","source":"name:E602"},
    {"phrase":"e603","reason":"placeholder_name","source":"name:E603"},
    {"phrase":"e604","reason":"placeholder_name","source":"name:E604"},
    {"phrase":"e605","reason":"placeholder_name","source":"name:E605"},
    {"phrase":"e606","reason":"placeholder_name","source":"name:E606"},
    {"phrase":"e607","reason":"placeholder_name","source":"name:E607"},
    {"phrase":"e608","reason":"placeholder_name","source":"name:E608"},
    {"phrase":"e609","reason":"placeholder_name","source":"name:E609"},
    {"phrase":"e610","reason":"placeholder_name","source":"name:E610"},
    {"phrase":"e611","reason":"placeholder_name","source":"name:E611"},
    {"phrase":"e612","reason":"placeholder_name","source":"name:E612"},
    {"phrase":"e613","reason":"placeholder_name","source":"name:E613"},
    {"phrase":"e614","reason":"placeholder_name","source":"name:E614"},
    {"phrase":"e615","reason":"placeholder_name","source":"name:E615"},
    {"phrase":"e616","reason":"placeholder_name","source":"name:E616"},
    {"phrase":"e617","reason":"placeholder_name","source":"name:E617"},
    {"phrase":"e618","reason":"placeholder_name","source":"name:E618"},
    {"phrase":"e619","reason":"placeholder_name","source":"name:E619"},
    {"phrase":"e636","reason":"placeholder_name","source":"name:E636"},
    {"phrase":"e637","reason":"placeholder_name","source":"name:E637"},
    {"phrase":"e638","reason":"placeholder_name","source":"name:E638"},
    {"phrase":"e639","reason":"placeholder_name","source":"name:E639"},
    {"phrase":"e642","reason":"placeholder_name","source":"name:E642"},
    {"phrase":"e643","reason":"placeholder_name","source":"name:E643"},
    {"phrase":"e644","reason":"placeholder_name","source":"name:E644"},
    {"phrase":"e645","reason":"placeholder_name","source":"name:E645"},
    {"phrase":"e646","reason":"placeholder_name","source":"name:E646"},
    {"phrase":"e647","reason":"placeholder_name","source":"name:E647"},
    {"phrase":"e648","reason":"placeholder_name","source":"name:E648"},
    {"phrase":"e649","reason":"placeholder_name","source":"name:E649"},
    {"phrase":"e651","reason":"placeholder_name","source":"name:E651"},
    {"phrase":"e652","reason":"placeholder_name","source":"name:E652"},
    {"phrase":"e653","reason":"placeholder_name","source":"name:E653"},
    {"phrase":"e654","reason":"placeholder_name","source":"name:E654"},
    {"phrase":"e655","reason":"placeholder_name","source":"name:E655"},
    {"phrase":"e656","reason":"placeholder_name","source":"name:E656"},
    {"phrase":"e657","reason":"placeholder_name","source":"name:E657"},
    {"phrase":"e658","reason":"placeholder_name","source":"name:E658"},
    {"phrase":"e659","reason":"placeholder_name","source":"name:E659"},
    {"phrase":"e660","reason":"placeholder_name","source":"name:E660"},
    {"phrase":"e661","reason":"placeholder_name","source":"name:E661"},
    {"phrase":"e662","reason":"placeholder_name","source":"name:E662"},
    {"phrase":"e663","reason":"placeholder_name","source":"name:E663"},
    {"phrase":"e664","reason":"placeholder_name","source":"name:E664"},
    {"phrase":"e665","reason":"placeholder_name","source":"name:E665"},
    {"phrase":"e666","reason":"placeholder_name","source":"name:E666"},
    {"phrase":"e667","reason":"placeholder_name","source":"name:E667"},
    {"phrase":"e668","reason":"placeholder_name","source":"name:E668"},
    {"phrase":"e669","reason":"placeholder_name","source":"name:E669"},
    {"phrase":"e670","reason":"placeholder_name","source":"name:E670"},
    {"phrase":"e671","reason":"placeholder_name","source":"name:E671"},
    {"phrase":"e672","reason":"placeholder_name","source":"name:E672"},
    {"phrase":"e673","reason":"placeholder_name","source":"name:E673"},
    {"phrase":"e674","reason":"placeholder_name","source":"name:E674"},
    {"phrase":"e675","reason":"placeholder_name","source":"name:E675"},
    {"phrase":"e676","reason":"placeholder_name","source":"name:E676"},
    {"phrase":"e677","reason":"placeholder_name","source":"name:E677"},
    {"phrase":"e678","reason":"placeholder_name","source":"name:E678"},
    {"phrase":"e679","reason":"placeholder_name","source":"name:E679"},
    {"phrase":"e680","reason":"placeholder_name","source":"name:E680"},
    {"phrase":"e681","reason":"placeholder_name","source":"name:E681"},
    {"phrase":"e682","reason":"placeholder_name","source":"name:E682"},
    {"phrase":"e683","reason":"placeholder_name","source":"name:E683"},
    {"phrase":"e684","reason":"placeholder_name","source":"name:E684"},
    {"phrase":"e685","reason":"placeholder_name","source":"name:E685"},
    {"phrase":"e686","reason":"placeholder_name","source":"name:E686"},
    {"phrase":"e687","reason":"placeholder_name","source":"name:E687"},
    {"phrase":"e688","reason":"placeholder_name","source":"name:E688"},
    {"phrase":"e689","reason":"placeholder_name","source":"name:E689"},
    {"phrase":"e690","reason":"placeholder_name","source":"name:E690"},
    {"phrase":"e691","reason":"placeholder_name","source":"name:E691"},
    {"phrase":"e692","reason":"placeholder_name","source":"name:E692"},
    {"phrase":"e693","reason":"placeholder_name","source":"name:E693"},
    {"phrase":"e694","reason":"placeholder_name","source":"name:E694"},
    {"phrase":"e695","reason":"placeholder_name","source":"name:E695"},
    {"phrase":"e696","reason":"placeholder_name","source":"name:E696"},
    {"phrase":"e697","reason":"placeholder_name","source":"name:E697"},
    {"phrase":"e698","reason":"placeholder_name","source":"name:E698"},
    {"phrase":"e699","reason":"placeholder_name","source":"name:E699"},
    {"phrase":"e800","reason":"placeholder_name","source":"name:E800"},
    {"phrase":"e801","reason":"placeholder_name","source":"name:E801"},
    {"phrase":"e802","reason":"placeholder_name","source":"name:E802"},
    {"phrase":"e803","reason":"placeholder_name","source":"name:E803"},
    {"phrase":"e804","reason":"placeholder_name","source":"name:E804"},
    {"phrase":"e805","reason":"placeholder_name","source":"name:E805"},
    {"phrase":"e806","reason":"placeholder_name","source":"name:E806"},
    {"phrase":"e807","reason":"placeholder_name","source":"name:E807"},
    {"phrase":"e808","reason":"placeholder_name","source":"name:E808"},
    {"phrase":"e809","reason":"placeholder_name","source":"name:E809"},
    {"phrase":"e810","reason":"placeholder_name","source":"name:E810"},
    {"phrase":"e811","reason":"placeholder_name","source":"name:E811"},
    {"phrase":"e812","reason":"placeholder_name","source":"name:E812"},
    {"phrase":"e813","reason":"placeholder_name","source":"name:E813"},
    {"phrase":"e814","reason":"placeholder_name","source":"name:E814"},
    {"phrase":"e815","reason":"placeholder_name","source":"name:E815"},
    {"phrase":"e816","reason":"placeholder_name","source":"name:E816"},
    {"phrase":"e817","reason":"placeholder_name","source":"name:E817"},
    {"phrase":"e818","reason":"placeholder_name","source":"name:E818"},
    {"phrase":"e819","reason":"placeholder_name","source":"name:E819"},
    {"phrase":"e820","reason":"placeholder_name","source":"name:E820"},
    {"phrase":"e821","reason":"placeholder_name","source":"name:E821"},
    {"phrase":"e822","reason":"placeholder_name","source":"name:E822"},
    {"phrase":"e823","reason":"placeholder_name","source":"name:E823"},
    {"phrase":"e824","reason":"placeholder_name","source":"name:E824"},
    {"phrase":"e825","reason":"placeholder_name","source":"name:E825"},
    {"phrase":"e826","reason":"placeholder_name","source":"name:E826"},
    {"phrase":"e827","reason":"placeholder_name","source":"name:E827"},
    {"phrase":"e828","reason":"placeholder_name","source":"name:E828"},
    {"phrase":"e829","reason":"placeholder_name","source":"name:E829"},
    {"phrase":"e830","reason":"placeholder_name","source":"name:E830"},
    {"phrase":"e831","reason":"placeholder_name","source":"name:E831"},
    {"phrase":"e832","reason":"placeholder_name","source":"name:E832"},
    {"phrase":"e833","reason":"placeholder_name","source":"name:E833"},
    {"phrase":"e834","reason":"placeholder_name","source":"name:E834"},
    {"phrase":"e835","reason":"placeholder_name","source":"name:E835"},
    {"phrase":"e836","reason":"placeholder_name","source":"name:E836"},
    {"phrase":"e837","reason":"placeholder_name","source":"name:E837"},
    {"phrase":"e838","reason":"placeholder_name","source":"name:E838"},
    {"phrase":"e839","reason":"placeholder_name","source":"name:E839"},
    {"phrase":"e840","reason":"placeholder_name","source":"name:E840"},
    {"phrase":"e841","reason":"placeholder_name","source":"name:E841"},
    {"phrase":"e842","reason":"placeholder_name","source":"name:E842"},
    {"phrase":"e843","reason":"placeholder_name","source":"name:E843"},
    {"phrase":"e844","reason":"placeholder_name","source":"name:E844"},
    {"phrase":"e845","reason":"placeholder_name","source":"name:E845"},
    {"phrase":"e846","reason":"placeholder_name","source":"name:E846"},
    {"phrase":"e847","reason":"placeholder_name","source":"name:E847"},
    {"phrase":"e848","reason":"placeholder_name","source":"name:E848"},
    {"phrase":"e849","reason":"placeholder_name","source":"name:E849"},
    {"phrase":"e850","reason":"placeholder_name","source":"name:E850"},
    {"phrase":"e851","reason":"placeholder_name","source":"name:E851"},
    {"phrase":"e852","reason":"placeholder_name","source":"name:E852"},
    {"phrase":"e853","reason":"placeholder_name","source":"name:E853"},
    {"phrase":"e854","reason":"placeholder_name","source":"name:E854"},
    {"phrase":"e855","reason":"placeholder_name","source":"name:E855"},
    {"phrase":"e856","reason":"placeholder_name","source":"name:E856"},
    {"phrase":"e857","reason":"placeholder_name","source":"name:E857"},
    {"phrase":"e858","reason":"placeholder_name","source":"name:E858"},
    {"phrase":"e859","reason":"placeholder_name","source":"name:E859"},
    {"phrase":"e860","reason":"placeholder_name","source":"name:E860"},
    {"phrase":"e861","reason":"placeholder_name","source":"name:E861"},
    {"phrase":"e862","reason":"placeholder_name","source":"name:E862"},
    {"phrase":"e863","reason":"placeholder_name","source":"name:E863"},
    {"phrase":"e864","reason":"placeholder_name","source":"name:E864"},
    {"phrase":"e865","reason":"placeholder_name","source":"name:E865"},
    {"phrase":"e866","reason":"placeholder_name","source":"name:E866"},
    {"phrase":"e867","reason":"placeholder_name","source":"name:E867"},
    {"phrase":"e868","reason":"placeholder_name","source":"name:E868"},
    {"phrase":"e869","reason":"placeholder_name","source":"name:E869"},
    {"phrase":"e870","reason":"placeholder_name","source":"name:E870"},
    {"phrase":"e871","reason":"placeholder_name","source":"name:E871"},
    {"phrase":"e872","reason":"placeholder_name","source":"name:E872"},
    {"phrase":"e873","reason":"placeholder_name","source":"name:E873"},
    {"phrase":"e874","reason":"placeholder_name","source":"name:E874"},
    {"phrase":"e875","reason":"placeholder_name","source":"name:E875"},
    {"phrase":"e876","reason":"placeholder_name","source":"name:E876"},
    {"phrase":"e877","reason":"placeholder_name","source":"name:E877"},
    {"phrase":"e878","reason":"placeholder_name","source":"name:E878"},
    {"phrase":"e879","reason":"placeholder_name","source":"name:E879"},
    {"phrase":"e880","reason":"placeholder_name","source":"name:E880"},
    {"phrase":"e881","reason":"placeholder_name","source":"name:E881"},
    {"phrase":"e882","reason":"placeholder_name","source":"name:E882"},
    {"phrase":"e883","reason":"placeholder_name","source":"name:E883"},
    {"phrase":"e884","reason":"placeholder_name","source":"name:E884"},
    {"phrase":"e885","reason":"placeholder_name","source":"name:E885"},
    {"phrase":"e886","reason":"placeholder_name","source":"name:E886"},
    {"phrase":"e887","reason":"placeholder_name","source":"name:E887"},
    {"phrase":"e888","reason":"placeholder_name","source":"name:E888"},
    {"phrase":"e889","reason":"placeholder_name","source":"name:E889"},
    {"phrase":"e890","reason":"placeholder_name","source":"name:E890"},
    {"phrase":"e891","reason":"placeholder_name","source":"name:E891"},
    {"phrase":"e892","reason":"placeholder_name","source":"name:E892"},
    {"phrase":"e893","reason":"placeholder_name","source":"name:E893"},
    {"phrase":"e894","reason":"placeholder_name","source":"name:E894"},
    {"phrase":"e895","reason":"placeholder_name","source":"name:E895"},
    {"phrase":"e896","reason":"placeholder_name","source":"name:E896"},
    {"phrase":"e897","reason":"placeholder_name","source":"name:E897"},
    {"phrase":"e898","reason":"placeholder_name","source":"name:E898"},
    {"phrase":"e899","reason":"placeholder_name","source":"name:E899"},
    {"phrase":"e906","reason":"placeholder_name","source":"name:E906"},
    {"phrase":"e908","reason":"placeholder_name","source":"name:E908"},
    {"phrase":"e909","reason":"placeholder_name","source":"name:E909"},
    {"phrase":"e910","reason":"placeholder_name","source":"name:E910"},
    {"phrase":"e911","reason":"placeholder_name","source":"name:E911"},
    {"phrase":"e913","reason":"placeholder_name","source":"name:E913"},
    {"phrase":"e915","reason":"placeholder_name","source":"name:E915"},
    {"phrase":"e916","reason":"placeholder_name","source":"name:E916"},
    {"phrase":"e917","reason":"placeholder_name","source":"name:E917"},
    {"phrase":"e918","reason":"placeholder_name","source":"name:E918"},
    {"phrase":"e919","reason":"placeholder_name","source":"name:E919"},
    {"phrase":"e922","reason":"placeholder_name","source":"name:E922"},
    {"phrase":"e923","reason":"placeholder_name","source":"name:E923"},
    {"phrase":"e929","reason":"placeholder_name","source":"name:E929"},
    {"phrase":"e931","reason":"placeholder_name","source":"name:E931"},
    {"phrase":"e932","reason":"placeholder_name","source":"name:E932"},
    {"phrase":"e933","reason":"placeholder_name","source":"name:E933"},
    {"phrase":"e934","reason":"placeholder_name","source":"name:E934"},
    {"phrase":"e935","reason":"placeholder_name","source":"name:E935"},
    {"phrase":"e936","reason":"placeholder_name","source":"name:E936"},
    {"phrase":"e937","reason":"placeholder_name","source":"name:E937"},
    {"phrase":"e940","reason":"placeholder_name","source":"name:E940"},
    {"phrase":"e945","reason":"placeholder_name","source":"name:E945"},
    {"phrase":"e946","reason":"placeholder_name","source":"name:E946"},
    {"phrase":"e947","reason":"placeholder_name","source":"name:E947"},
    {"phrase":"e963","reason":"placeholder_name","source":"name:E963"},
    {"phrase":"e964","reason":"placeholder_name","source":"name:E964"},
    {"phrase":"e969","reason":"placeholder_name","source":"name:E969"},
    {"phrase":"e970","reason":"placeholder_name","source":"name:E970"},
    {"phrase":"e971","reason":"placeholder_name","source":"name:E971"},
    {"phrase":"e972","reason":"placeholder_name","source":"name:E972"},
    {"phrase":"e973","reason":"placeholder_name","source":"name:E973"},
    {"phrase":"e974","reason":"placeholder_name","source":"name:E974"},
    {"phrase":"e975","reason":"placeholder_name","source":"name:E975"},
    {"phrase":"e976","reason":"placeholder_name","source":"name:E976"},
    {"phrase":"e977","reason":"placeholder_name","source":"name:E977"},
    {"phrase":"e978","reason":"placeholder_name","source":"name:E978"},
    {"phrase":"e979","reason":"placeholder_name","source":"name:E979"},
    {"phrase":"e980","reason":"placeholder_name","source":"name:E980"},
    {"phrase":"e981","reason":"placeholder_name","source":"name:E981"},
    {"phrase":"e982","reason":"placeholder_name","source":"name:E982"},
    {"phrase":"e983","reason":"placeholder_name","source":"name:E983"},
    {"phrase":"e984","reason":"placeholder_name","source":"name:E984"},
    {"phrase":"e985","reason":"placeholder_name","source":"name:E985"},
    {"phrase":"e986","reason":"placeholder_name","source":"name:E986"},
    {"phrase":"e987","reason":"placeholder_name","source":"name:E987"},
    {"phrase":"e988","reason":"placeholder_name","source":"name:E988"},
    {"phrase":"e989","reason":"placeholder_name","source":"name:E989"},
    {"phrase":"e990","reason":"placeholder_name","source":"name:E990"},
    {"phrase":"e991","reason":"placeholder_name","source":"name:E991"},
    {"phrase":"e992","reason":"placeholder_name","source":"name:E992"},
    {"phrase":"e993","reason":"placeholder_name","source":"name:E993"},
    {"phrase":"e994","reason":"placeholder_name","source":"name:E994"},
    {"phrase":"e995","reason":"placeholder_name","source":"name:E995"},
    {"phrase":"e996","reason":"placeholder_name","source":"name:E996"},
    {"phrase":"e997","reason":"placeholder_name","source":"name:E997"},
    {"phrase":"e998","reason":"placeholder_name","source":"name:E998"},
  ] as const);
