// Comprehensive E-number additives database
// Based on EU food additive regulations and industry standards

export interface AdditiveInfo {
  name: string;
  category: string;
  description: string;
  safety: 'safe' | 'caution' | 'avoid';
  uses?: string[];
  concerns?: string[];
  alternatives?: string;
}

export const ADDITIVE_DATABASE: Record<string, AdditiveInfo> = {
  // E100-E199: Colors
  'e100': { name: 'Curcumin (Turmeric)', category: 'Color', description: 'Natural yellow-orange color derived from turmeric root. Used in curry powders, mustard, and processed foods.', safety: 'safe', uses: ['Curry powders', 'Mustard', 'Processed foods'] },
  'e101': { name: 'Riboflavin (Vitamin B2)', category: 'Color', description: 'Natural yellow color and essential vitamin. Found naturally in milk, eggs, and green vegetables.', safety: 'safe', uses: ['Cereals', 'Dairy products', 'Energy drinks'] },
  'e102': { name: 'Tartrazine', category: 'Color', description: 'Artificial yellow color (FD&C Yellow 5). May cause allergic reactions, hyperactivity in children, and asthma attacks in sensitive individuals.', safety: 'caution', concerns: ['Hyperactivity in children', 'Allergic reactions', 'Asthma'], alternatives: 'Natural colors like turmeric' },
  'e104': { name: 'Quinoline Yellow', category: 'Color', description: 'Artificial yellow-green color. May cause hyperactivity in children and allergic reactions. Banned in some countries.', safety: 'caution', concerns: ['Hyperactivity', 'Allergic reactions'] },
  'e110': { name: 'Sunset Yellow FCF', category: 'Color', description: 'Artificial orange color (FD&C Yellow 6). May cause allergic reactions, hyperactivity in children, and skin rashes.', safety: 'caution', concerns: ['Hyperactivity', 'Allergic reactions', 'Skin rashes'] },
  'e120': { name: 'Cochineal / Carmine', category: 'Color', description: 'Red color extracted from crushed cochineal insects. May cause severe allergic reactions, especially in asthmatics. Not suitable for vegetarians/vegans.', safety: 'caution', concerns: ['Severe allergic reactions', 'Asthma triggers', 'Not vegetarian'], alternatives: 'Beetroot extract, paprika' },
  'e122': { name: 'Azorubine / Carmoisine', category: 'Color', description: 'Artificial red color. May cause allergic reactions and hyperactivity in children. Banned in some countries.', safety: 'caution', concerns: ['Hyperactivity', 'Allergic reactions'] },
  'e124': { name: 'Ponceau 4R', category: 'Color', description: 'Artificial red color. May cause allergic reactions and hyperactivity in children. Banned in the US.', safety: 'caution', concerns: ['Hyperactivity', 'Allergic reactions'] },
  'e129': { name: 'Allura Red AC', category: 'Color', description: 'Artificial red color (FD&C Red 40). May cause hyperactivity in children and allergic reactions.', safety: 'caution', concerns: ['Hyperactivity', 'Allergic reactions'] },
  'e131': { name: 'Patent Blue V', category: 'Color', description: 'Artificial blue color. May cause allergic reactions. Banned in some countries.', safety: 'caution', concerns: ['Allergic reactions'] },
  'e132': { name: 'Indigotine / Indigo Carmine', category: 'Color', description: 'Artificial blue color. May cause allergic reactions, nausea, and skin rashes.', safety: 'caution', concerns: ['Allergic reactions', 'Nausea', 'Skin rashes'] },
  'e133': { name: 'Brilliant Blue FCF', category: 'Color', description: 'Artificial blue color (FD&C Blue 1). Generally considered safe, but may cause allergic reactions in sensitive individuals.', safety: 'safe' },
  'e140': { name: 'Chlorophyll', category: 'Color', description: 'Natural green color from plants. Completely safe and natural.', safety: 'safe', uses: ['Green foods', 'Herbal products'] },
  'e141': { name: 'Copper Complexes of Chlorophyll', category: 'Color', description: 'Green color stabilized with copper. Generally safe in small amounts.', safety: 'safe' },
  'e142': { name: 'Green S', category: 'Color', description: 'Artificial green color. May cause allergic reactions. Banned in some countries.', safety: 'caution', concerns: ['Allergic reactions'] },
  'e150a': { name: 'Caramel I (Plain)', category: 'Color', description: 'Natural brown color from heated sugar. Generally safe.', safety: 'safe', uses: ['Cola drinks', 'Sauces', 'Baked goods'] },
  'e150b': { name: 'Caramel II (Caustic Sulfite)', category: 'Color', description: 'Brown color made with sulfite. May cause issues for sulfite-sensitive individuals.', safety: 'caution', concerns: ['Sulfite sensitivity'] },
  'e150c': { name: 'Caramel III (Ammonia)', category: 'Color', description: 'Brown color made with ammonia. May contain small amounts of 4-MEI, a potential carcinogen.', safety: 'caution', concerns: ['Potential carcinogen 4-MEI'] },
  'e150d': { name: 'Caramel IV (Ammonia Sulfite)', category: 'Color', description: 'Brown color made with both ammonia and sulfite. May contain 4-MEI and affect sulfite-sensitive individuals.', safety: 'caution', concerns: ['Potential carcinogen 4-MEI', 'Sulfite sensitivity'] },
  'e151': { name: 'Brilliant Black BN', category: 'Color', description: 'Artificial black color. May cause allergic reactions. Banned in some countries.', safety: 'caution', concerns: ['Allergic reactions'] },
  'e153': { name: 'Vegetable Carbon', category: 'Color', description: 'Natural black color from charred vegetables. Generally safe.', safety: 'safe' },
  'e155': { name: 'Brown HT', category: 'Color', description: 'Artificial brown color. May cause allergic reactions. Banned in the US.', safety: 'caution', concerns: ['Allergic reactions'] },
  'e160a': { name: 'Carotenes (Alpha, Beta, Gamma)', category: 'Color', description: 'Natural orange color from carrots and other plants. Source of vitamin A. Completely safe.', safety: 'safe', uses: ['Margarine', 'Cheese', 'Juices'] },
  'e160b': { name: 'Annatto / Bixin', category: 'Color', description: 'Natural orange-yellow color from annatto seeds. May cause allergic reactions in rare cases.', safety: 'safe' },
  'e160c': { name: 'Paprika Extract', category: 'Color', description: 'Natural red-orange color from paprika. Completely safe.', safety: 'safe' },
  'e160d': { name: 'Lycopene', category: 'Color', description: 'Natural red color from tomatoes. Antioxidant with health benefits. Completely safe.', safety: 'safe' },
  'e160e': { name: 'Beta-Apo-8\'-Carotenal', category: 'Color', description: 'Synthetic carotenoid. Generally safe.', safety: 'safe' },
  'e161b': { name: 'Lutein', category: 'Color', description: 'Natural yellow color from marigolds. Supports eye health. Completely safe.', safety: 'safe' },
  'e162': { name: 'Beetroot Red / Betanin', category: 'Color', description: 'Natural red color from beets. Completely safe and natural.', safety: 'safe' },
  'e163': { name: 'Anthocyanins', category: 'Color', description: 'Natural purple/red/blue colors from berries and grapes. Antioxidant properties. Completely safe.', safety: 'safe' },
  'e170': { name: 'Calcium Carbonate', category: 'Color / Acidity Regulator', description: 'Natural white color and calcium supplement. Completely safe.', safety: 'safe', uses: ['Baking powder', 'Calcium supplements'] },
  'e171': { name: 'Titanium Dioxide', category: 'Color', description: 'White color. Banned in EU (2022) due to potential genotoxicity concerns. Still used in some countries.', safety: 'avoid', concerns: ['Potential genotoxicity', 'Banned in EU'], alternatives: 'Natural alternatives' },
  'e172': { name: 'Iron Oxides', category: 'Color', description: 'Natural red, yellow, and black colors. Generally safe in small amounts.', safety: 'safe' },
  'e173': { name: 'Aluminium', category: 'Color', description: 'Metallic silver color. May accumulate in body. Avoid if possible.', safety: 'caution', concerns: ['May accumulate in body'] },
  'e174': { name: 'Silver', category: 'Color', description: 'Metallic silver color for decoration. Generally safe in small amounts.', safety: 'safe' },
  'e175': { name: 'Gold', category: 'Color', description: 'Metallic gold color for decoration. Generally safe in small amounts.', safety: 'safe' },
  'e180': { name: 'Lithol Rubine BK', category: 'Color', description: 'Artificial red color. May cause allergic reactions. Banned in some countries.', safety: 'caution', concerns: ['Allergic reactions'] },

  // E200-E299: Preservatives
  'e200': { name: 'Sorbic Acid', category: 'Preservative', description: 'Natural preservative from berries. Prevents mold and yeast growth. Generally safe in small amounts.', safety: 'safe', uses: ['Cheese', 'Wine', 'Baked goods'] },
  'e202': { name: 'Potassium Sorbate', category: 'Preservative', description: 'Salt of sorbic acid. Prevents mold and yeast growth. Generally safe.', safety: 'safe', uses: ['Cheese', 'Yogurt', 'Dried fruit'] },
  'e203': { name: 'Calcium Sorbate', category: 'Preservative', description: 'Calcium salt of sorbic acid. Prevents mold growth. Generally safe.', safety: 'safe' },
  'e210': { name: 'Benzoic Acid', category: 'Preservative', description: 'Natural preservative from berries. May cause hyperactivity in children when combined with colors. May trigger asthma.', safety: 'caution', concerns: ['Hyperactivity with colors', 'Asthma triggers'] },
  'e211': { name: 'Sodium Benzoate', category: 'Preservative', description: 'Common preservative. May cause hyperactivity in children when combined with artificial colors. May form benzene (carcinogen) with vitamin C.', safety: 'caution', concerns: ['Hyperactivity with colors', 'May form benzene'], alternatives: 'Natural preservatives' },
  'e212': { name: 'Potassium Benzoate', category: 'Preservative', description: 'Potassium salt of benzoic acid. Similar concerns to sodium benzoate.', safety: 'caution', concerns: ['Hyperactivity with colors'] },
  'e213': { name: 'Calcium Benzoate', category: 'Preservative', description: 'Calcium salt of benzoic acid. Similar concerns to sodium benzoate.', safety: 'caution', concerns: ['Hyperactivity with colors'] },
  'e214': { name: 'Ethyl p-Hydroxybenzoate', category: 'Preservative', description: 'Paraben preservative. May cause allergic reactions and has estrogenic effects. Use with caution.', safety: 'caution', concerns: ['Allergic reactions', 'Estrogenic effects'] },
  'e215': { name: 'Sodium Ethyl p-Hydroxybenzoate', category: 'Preservative', description: 'Sodium salt of paraben. Similar concerns to other parabens.', safety: 'caution', concerns: ['Allergic reactions', 'Estrogenic effects'] },
  'e218': { name: 'Methyl p-Hydroxybenzoate', category: 'Preservative', description: 'Paraben preservative. May cause allergic reactions and has estrogenic effects.', safety: 'caution', concerns: ['Allergic reactions', 'Estrogenic effects'] },
  'e219': { name: 'Sodium Methyl p-Hydroxybenzoate', category: 'Preservative', description: 'Sodium salt of paraben. Similar concerns to other parabens.', safety: 'caution', concerns: ['Allergic reactions', 'Estrogenic effects'] },
  'e220': { name: 'Sulfur Dioxide', category: 'Preservative', description: 'Preservative and antioxidant. May trigger asthma attacks and cause breathing difficulties in sensitive individuals. Destroys vitamin B1.', safety: 'caution', concerns: ['Asthma triggers', 'Breathing difficulties', 'Destroys vitamin B1'] },
  'e221': { name: 'Sodium Sulfite', category: 'Preservative', description: 'Preservative. May trigger asthma and cause allergic reactions. Destroys vitamin B1.', safety: 'caution', concerns: ['Asthma triggers', 'Allergic reactions'] },
  'e222': { name: 'Sodium Hydrogen Sulfite', category: 'Preservative', description: 'Preservative. May trigger asthma and cause allergic reactions.', safety: 'caution', concerns: ['Asthma triggers', 'Allergic reactions'] },
  'e223': { name: 'Sodium Metabisulfite', category: 'Preservative', description: 'Preservative. May trigger asthma and cause allergic reactions.', safety: 'caution', concerns: ['Asthma triggers', 'Allergic reactions'] },
  'e224': { name: 'Potassium Metabisulfite', category: 'Preservative', description: 'Preservative. May trigger asthma and cause allergic reactions.', safety: 'caution', concerns: ['Asthma triggers', 'Allergic reactions'] },
  'e225': { name: 'Potassium Sulfite', category: 'Preservative', description: 'Preservative. May trigger asthma and cause allergic reactions.', safety: 'caution', concerns: ['Asthma triggers', 'Allergic reactions'] },
  'e226': { name: 'Calcium Sulfite', category: 'Preservative', description: 'Preservative. May trigger asthma and cause allergic reactions.', safety: 'caution', concerns: ['Asthma triggers', 'Allergic reactions'] },
  'e227': { name: 'Calcium Hydrogen Sulfite', category: 'Preservative', description: 'Preservative. May trigger asthma and cause allergic reactions.', safety: 'caution', concerns: ['Asthma triggers', 'Allergic reactions'] },
  'e228': { name: 'Potassium Hydrogen Sulfite', category: 'Preservative', description: 'Preservative. May trigger asthma and cause allergic reactions.', safety: 'caution', concerns: ['Asthma triggers', 'Allergic reactions'] },
  'e230': { name: 'Biphenyl / Diphenyl', category: 'Preservative', description: 'Used to preserve citrus fruits. May cause skin irritation. Not allowed in most foods.', safety: 'caution', concerns: ['Skin irritation'] },
  'e231': { name: 'Ortho-Phenylphenol', category: 'Preservative', description: 'Used on citrus fruits. May cause skin irritation. Not allowed in most foods.', safety: 'caution', concerns: ['Skin irritation'] },
  'e232': { name: 'Sodium Ortho-Phenylphenate', category: 'Preservative', description: 'Used on citrus fruits. May cause skin irritation.', safety: 'caution', concerns: ['Skin irritation'] },
  'e233': { name: 'Thiabendazole', category: 'Preservative', description: 'Antifungal used on fruits. May cause nausea and dizziness. Not allowed in most foods.', safety: 'caution', concerns: ['Nausea', 'Dizziness'] },
  'e234': { name: 'Nisin', category: 'Preservative', description: 'Natural preservative from bacteria. Prevents spoilage in cheese and dairy. Generally safe.', safety: 'safe', uses: ['Cheese', 'Dairy products'] },
  'e235': { name: 'Natamycin', category: 'Preservative', description: 'Antifungal preservative. Prevents mold on cheese. Generally safe.', safety: 'safe', uses: ['Cheese'] },
  'e239': { name: 'Hexamethylene Tetramine', category: 'Preservative', description: 'Used in some cheeses. May form formaldehyde. Use with caution.', safety: 'caution', concerns: ['May form formaldehyde'] },
  'e242': { name: 'Dimethyl Dicarbonate', category: 'Preservative', description: 'Used in beverages. Breaks down quickly. Generally safe.', safety: 'safe' },
  'e249': { name: 'Potassium Nitrite', category: 'Preservative', description: 'Prevents botulism in cured meats. May form carcinogenic nitrosamines when heated. Use in moderation.', safety: 'caution', concerns: ['May form nitrosamines (carcinogens)'], uses: ['Cured meats', 'Bacon'] },
  'e250': { name: 'Sodium Nitrite', category: 'Preservative', description: 'Prevents botulism in cured meats. May form carcinogenic nitrosamines when heated. Use in moderation.', safety: 'caution', concerns: ['May form nitrosamines (carcinogens)'], uses: ['Cured meats', 'Bacon', 'Hot dogs'] },
  'e251': { name: 'Sodium Nitrate', category: 'Preservative', description: 'Used in cured meats. Converts to nitrite in body. Similar concerns to nitrites.', safety: 'caution', concerns: ['Converts to nitrite', 'May form nitrosamines'], uses: ['Cured meats'] },
  'e252': { name: 'Potassium Nitrate', category: 'Preservative', description: 'Used in cured meats. Converts to nitrite in body. Similar concerns to nitrites.', safety: 'caution', concerns: ['Converts to nitrite', 'May form nitrosamines'], uses: ['Cured meats'] },
  'e280': { name: 'Propionic Acid', category: 'Preservative', description: 'Natural preservative. Prevents mold in bread. Generally safe.', safety: 'safe', uses: ['Bread', 'Baked goods'] },
  'e281': { name: 'Sodium Propionate', category: 'Preservative', description: 'Prevents mold in bread. Generally safe.', safety: 'safe', uses: ['Bread', 'Baked goods'] },
  'e282': { name: 'Calcium Propionate', category: 'Preservative', description: 'Prevents mold in bread. Generally safe.', safety: 'safe', uses: ['Bread', 'Baked goods'] },
  'e283': { name: 'Potassium Propionate', category: 'Preservative', description: 'Prevents mold in bread. Generally safe.', safety: 'safe', uses: ['Bread', 'Baked goods'] },
  'e284': { name: 'Boric Acid', category: 'Preservative', description: 'Used in caviar. Toxic in large amounts. Banned in many countries.', safety: 'avoid', concerns: ['Toxic in large amounts'], uses: ['Caviar'] },
  'e285': { name: 'Sodium Tetraborate', category: 'Preservative', description: 'Used in caviar. Similar concerns to boric acid.', safety: 'avoid', concerns: ['Toxic in large amounts'] },
  'e290': { name: 'Carbon Dioxide', category: 'Preservative / Acidity Regulator', description: 'Natural gas used in carbonated drinks. Completely safe.', safety: 'safe', uses: ['Carbonated drinks'] },
  'e296': { name: 'Malic Acid', category: 'Acidity Regulator', description: 'Natural acid from apples. Completely safe.', safety: 'safe', uses: ['Fruit drinks', 'Candies'] },
  'e297': { name: 'Fumaric Acid', category: 'Acidity Regulator', description: 'Natural acid from plants. Completely safe.', safety: 'safe', uses: ['Baked goods', 'Gelatin desserts'] },

  // E300-E399: Antioxidants and Acidity Regulators
  'e300': { name: 'Ascorbic Acid (Vitamin C)', category: 'Antioxidant', description: 'Natural vitamin and antioxidant. Prevents browning and preserves color. Completely safe and beneficial.', safety: 'safe', uses: ['Fruit juices', 'Baked goods', 'Meat products'] },
  'e301': { name: 'Sodium Ascorbate', category: 'Antioxidant', description: 'Sodium salt of vitamin C. Completely safe.', safety: 'safe' },
  'e302': { name: 'Calcium Ascorbate', category: 'Antioxidant', description: 'Calcium salt of vitamin C. Completely safe.', safety: 'safe' },
  'e303': { name: 'Potassium Ascorbate', category: 'Antioxidant', description: 'Potassium salt of vitamin C. Completely safe.', safety: 'safe' },
  'e304': { name: 'Ascorbyl Palmitate', category: 'Antioxidant', description: 'Fat-soluble form of vitamin C. Completely safe.', safety: 'safe' },
  'e306': { name: 'Tocopherols (Vitamin E)', category: 'Antioxidant', description: 'Natural vitamin E from plants. Completely safe and beneficial.', safety: 'safe', uses: ['Oils', 'Cereals', 'Nuts'] },
  'e307': { name: 'Alpha-Tocopherol', category: 'Antioxidant', description: 'Natural form of vitamin E. Completely safe.', safety: 'safe' },
  'e308': { name: 'Gamma-Tocopherol', category: 'Antioxidant', description: 'Natural form of vitamin E. Completely safe.', safety: 'safe' },
  'e309': { name: 'Delta-Tocopherol', category: 'Antioxidant', description: 'Natural form of vitamin E. Completely safe.', safety: 'safe' },
  'e310': { name: 'Propyl Gallate', category: 'Antioxidant', description: 'Synthetic antioxidant. May cause allergic reactions and stomach issues.', safety: 'caution', concerns: ['Allergic reactions', 'Stomach issues'] },
  'e311': { name: 'Octyl Gallate', category: 'Antioxidant', description: 'Synthetic antioxidant. May cause allergic reactions.', safety: 'caution', concerns: ['Allergic reactions'] },
  'e312': { name: 'Dodecyl Gallate', category: 'Antioxidant', description: 'Synthetic antioxidant. May cause allergic reactions.', safety: 'caution', concerns: ['Allergic reactions'] },
  'e315': { name: 'Erythorbic Acid', category: 'Antioxidant', description: 'Synthetic form of vitamin C. Generally safe.', safety: 'safe' },
  'e316': { name: 'Sodium Erythorbate', category: 'Antioxidant', description: 'Sodium salt of erythorbic acid. Generally safe.', safety: 'safe' },
  'e319': { name: 'TBHQ (Tertiary Butylhydroquinone)', category: 'Antioxidant', description: 'Synthetic antioxidant. May cause nausea and vision problems in high doses.', safety: 'caution', concerns: ['Nausea', 'Vision problems in high doses'] },
  'e320': { name: 'BHA (Butylated Hydroxyanisole)', category: 'Antioxidant', description: 'Synthetic antioxidant. May be carcinogenic and cause allergic reactions. Use with caution.', safety: 'caution', concerns: ['Potential carcinogen', 'Allergic reactions'] },
  'e321': { name: 'BHT (Butylated Hydroxytoluene)', category: 'Antioxidant', description: 'Synthetic antioxidant. May be carcinogenic and cause allergic reactions. Use with caution.', safety: 'caution', concerns: ['Potential carcinogen', 'Allergic reactions'] },
  'e330': { name: 'Citric Acid', category: 'Acidity Regulator / Antioxidant', description: 'Natural acid from citrus fruits. Very common and completely safe. Used to preserve and flavor foods.', safety: 'safe', uses: ['Soft drinks', 'Jams', 'Candies', 'Frozen foods'] },
  'e331': { name: 'Sodium Citrate', category: 'Acidity Regulator', description: 'Sodium salt of citric acid. Generally safe.', safety: 'safe' },
  'e332': { name: 'Potassium Citrate', category: 'Acidity Regulator', description: 'Potassium salt of citric acid. Generally safe.', safety: 'safe' },
  'e333': { name: 'Calcium Citrate', category: 'Acidity Regulator', description: 'Calcium salt of citric acid. Generally safe.', safety: 'safe' },
  'e334': { name: 'Tartaric Acid', category: 'Acidity Regulator', description: 'Natural acid from grapes. Completely safe.', safety: 'safe', uses: ['Wine', 'Baking powder'] },
  'e335': { name: 'Sodium Tartrate', category: 'Acidity Regulator', description: 'Sodium salt of tartaric acid. Generally safe.', safety: 'safe' },
  'e336': { name: 'Potassium Tartrate', category: 'Acidity Regulator', description: 'Potassium salt of tartaric acid. Generally safe.', safety: 'safe' },
  'e337': { name: 'Sodium Potassium Tartrate', category: 'Acidity Regulator', description: 'Combined salt of tartaric acid. Generally safe.', safety: 'safe' },
  'e338': { name: 'Phosphoric Acid', category: 'Acidity Regulator', description: 'Used in cola drinks. May leach calcium from bones in excessive amounts.', safety: 'caution', concerns: ['May leach calcium'], uses: ['Cola drinks'] },
  'e339': { name: 'Sodium Phosphates', category: 'Acidity Regulator / Emulsifier', description: 'Used in processed foods. May cause digestive issues in large amounts.', safety: 'caution', concerns: ['Digestive issues'], uses: ['Processed meats', 'Cheese'] },
  'e340': { name: 'Potassium Phosphates', category: 'Acidity Regulator', description: 'Used in processed foods. May cause digestive issues in large amounts.', safety: 'caution', concerns: ['Digestive issues'] },
  'e341': { name: 'Calcium Phosphates', category: 'Acidity Regulator / Anti-caking', description: 'Used in baking powder and as calcium supplement. Generally safe.', safety: 'safe', uses: ['Baking powder', 'Calcium supplements'] },
  'e343': { name: 'Magnesium Phosphates', category: 'Acidity Regulator / Anti-caking', description: 'Used in processed foods. Generally safe.', safety: 'safe' },
  'e350': { name: 'Sodium Malate', category: 'Acidity Regulator', description: 'Sodium salt of malic acid. Generally safe.', safety: 'safe' },
  'e351': { name: 'Potassium Malate', category: 'Acidity Regulator', description: 'Potassium salt of malic acid. Generally safe.', safety: 'safe' },
  'e352': { name: 'Calcium Malate', category: 'Acidity Regulator', description: 'Calcium salt of malic acid. Generally safe.', safety: 'safe' },
  'e353': { name: 'Metatartaric Acid', category: 'Acidity Regulator', description: 'Used in wine. Generally safe.', safety: 'safe' },
  'e354': { name: 'Calcium Tartrate', category: 'Acidity Regulator', description: 'Calcium salt of tartaric acid. Generally safe.', safety: 'safe' },
  'e355': { name: 'Adipic Acid', category: 'Acidity Regulator', description: 'Used in baking powder and gelatin. Generally safe.', safety: 'safe' },
  'e356': { name: 'Sodium Adipate', category: 'Acidity Regulator', description: 'Sodium salt of adipic acid. Generally safe.', safety: 'safe' },
  'e357': { name: 'Potassium Adipate', category: 'Acidity Regulator', description: 'Potassium salt of adipic acid. Generally safe.', safety: 'safe' },
  'e363': { name: 'Succinic Acid', category: 'Acidity Regulator', description: 'Natural acid. Generally safe.', safety: 'safe' },
  'e365': { name: 'Sodium Fumarate', category: 'Acidity Regulator', description: 'Sodium salt of fumaric acid. Generally safe.', safety: 'safe' },
  'e366': { name: 'Potassium Fumarate', category: 'Acidity Regulator', description: 'Potassium salt of fumaric acid. Generally safe.', safety: 'safe' },
  'e367': { name: 'Calcium Fumarate', category: 'Acidity Regulator', description: 'Calcium salt of fumaric acid. Generally safe.', safety: 'safe' },
  'e370': { name: '1,4-Heptonolactone', category: 'Acidity Regulator', description: 'Used in some foods. Generally safe.', safety: 'safe' },
  'e375': { name: 'Niacin (Vitamin B3)', category: 'Color Retention Agent', description: 'Essential vitamin. Completely safe and beneficial.', safety: 'safe' },
  'e380': { name: 'Triammonium Citrate', category: 'Acidity Regulator', description: 'Ammonium salt of citric acid. Generally safe.', safety: 'safe' },
  'e385': { name: 'Calcium Disodium EDTA', category: 'Preservative / Antioxidant', description: 'Prevents metal-catalyzed oxidation. May cause digestive issues and mineral absorption problems.', safety: 'caution', concerns: ['Digestive issues', 'Mineral absorption problems'] },
  'e386': { name: 'Disodium EDTA', category: 'Preservative / Antioxidant', description: 'Prevents metal-catalyzed oxidation. May cause digestive issues.', safety: 'caution', concerns: ['Digestive issues'] },
  'e387': { name: 'Oxystearin', category: 'Antioxidant', description: 'Used in oils. Generally safe.', safety: 'safe' },
  'e388': { name: 'Thiodipropionic Acid', category: 'Antioxidant', description: 'Synthetic antioxidant. Generally safe.', safety: 'safe' },
  'e389': { name: 'Dilauryl Thiodipropionate', category: 'Antioxidant', description: 'Synthetic antioxidant. Generally safe.', safety: 'safe' },
  'e390': { name: 'Distearyl Thiodipropionate', category: 'Antioxidant', description: 'Synthetic antioxidant. Generally safe.', safety: 'safe' },
  'e391': { name: 'Phytic Acid', category: 'Antioxidant', description: 'Natural antioxidant from plants. May reduce mineral absorption.', safety: 'caution', concerns: ['May reduce mineral absorption'] },
  'e392': { name: 'Rosemary Extract', category: 'Antioxidant', description: 'Natural antioxidant from rosemary. Completely safe.', safety: 'safe' },
  'e399': { name: 'Calcium Lactobionate', category: 'Stabilizer', description: 'Used in some foods. Generally safe.', safety: 'safe' },

  // E400-E499: Thickeners, Stabilizers, and Emulsifiers
  'e400': { name: 'Alginic Acid', category: 'Thickener', description: 'Natural thickener from brown seaweed. Generally safe.', safety: 'safe', uses: ['Ice cream', 'Sauces', 'Desserts'] },
  'e401': { name: 'Sodium Alginate', category: 'Thickener', description: 'Sodium salt of alginic acid. Natural thickener from seaweed. Generally safe.', safety: 'safe', uses: ['Ice cream', 'Jellies'] },
  'e402': { name: 'Potassium Alginate', category: 'Thickener', description: 'Potassium salt of alginic acid. Generally safe.', safety: 'safe' },
  'e403': { name: 'Ammonium Alginate', category: 'Thickener', description: 'Ammonium salt of alginic acid. Generally safe.', safety: 'safe' },
  'e404': { name: 'Calcium Alginate', category: 'Thickener', description: 'Calcium salt of alginic acid. Generally safe.', safety: 'safe' },
  'e405': { name: 'Propylene Glycol Alginate', category: 'Thickener / Emulsifier', description: 'Modified alginate. Generally safe.', safety: 'safe' },
  'e406': { name: 'Agar', category: 'Thickener / Gelling Agent', description: 'Natural thickener from red seaweed. Completely safe and vegetarian alternative to gelatin.', safety: 'safe', uses: ['Jellies', 'Ice cream', 'Desserts'] },
  'e407': { name: 'Carrageenan', category: 'Thickener', description: 'Thickener from red seaweed. Some studies suggest it may cause inflammation and digestive issues, but generally considered safe by authorities.', safety: 'caution', concerns: ['May cause inflammation', 'Digestive issues'], uses: ['Ice cream', 'Yogurt', 'Plant milks'] },
  'e407a': { name: 'Processed Eucheuma Seaweed', category: 'Thickener', description: 'Processed form of carrageenan. Generally considered safer than regular carrageenan.', safety: 'safe' },
  'e410': { name: 'Locust Bean Gum / Carob Gum', category: 'Thickener', description: 'Natural thickener from carob seeds. Completely safe.', safety: 'safe', uses: ['Ice cream', 'Sauces', 'Desserts'] },
  'e412': { name: 'Guar Gum', category: 'Thickener', description: 'Natural thickener from guar beans. High in fiber. Completely safe and may help with digestion.', safety: 'safe', uses: ['Ice cream', 'Sauces', 'Gluten-free products'] },
  'e413': { name: 'Tragacanth', category: 'Thickener', description: 'Natural gum from tree sap. May cause allergic reactions in sensitive individuals.', safety: 'caution', concerns: ['Allergic reactions'] },
  'e414': { name: 'Gum Arabic / Acacia Gum', category: 'Thickener', description: 'Natural gum from acacia trees. Generally safe, but may cause allergic reactions in rare cases.', safety: 'safe', uses: ['Soft drinks', 'Candies', 'Glazes'] },
  'e415': { name: 'Xanthan Gum', category: 'Thickener', description: 'Fermented sugar thickener. Generally safe in normal amounts. May cause digestive issues in large quantities.', safety: 'safe', uses: ['Gluten-free products', 'Sauces', 'Salad dressings'] },
  'e416': { name: 'Karaya Gum', category: 'Thickener', description: 'Natural gum from tree sap. May cause allergic reactions.', safety: 'caution', concerns: ['Allergic reactions'] },
  'e417': { name: 'Tara Gum', category: 'Thickener', description: 'Natural thickener from tara seeds. Generally safe.', safety: 'safe' },
  'e418': { name: 'Gellan Gum', category: 'Thickener / Gelling Agent', description: 'Fermented thickener. Generally safe.', safety: 'safe', uses: ['Desserts', 'Jellies'] },
  'e420': { name: 'Sorbitol', category: 'Sweetener / Humectant', description: 'Sugar alcohol from fruits. May cause digestive issues, bloating, and diarrhea in large amounts. Safe for diabetics.', safety: 'caution', concerns: ['Digestive issues', 'Bloating', 'Diarrhea'], uses: ['Sugar-free products', 'Chewing gum'] },
  'e421': { name: 'Mannitol', category: 'Sweetener', description: 'Sugar alcohol. May cause digestive issues, bloating, and diarrhea in large amounts.', safety: 'caution', concerns: ['Digestive issues', 'Bloating', 'Diarrhea'], uses: ['Sugar-free products'] },
  'e422': { name: 'Glycerol / Glycerin', category: 'Humectant', description: 'Natural compound that retains moisture. Completely safe.', safety: 'safe', uses: ['Baked goods', 'Candies'] },
  'e425': { name: 'Konjac / Konjac Gum', category: 'Thickener', description: 'Natural thickener from konjac root. High in fiber. May cause choking if not properly prepared. Generally safe.', safety: 'caution', concerns: ['Choking hazard if not prepared'], uses: ['Noodles', 'Jellies'] },
  'e426': { name: 'Soybean Hemicellulose', category: 'Thickener', description: 'Natural thickener from soybeans. Generally safe.', safety: 'safe' },
  'e427': { name: 'Cassia Gum', category: 'Thickener', description: 'Natural thickener from cassia seeds. Generally safe.', safety: 'safe' },
  'e432': { name: 'Polysorbate 20', category: 'Emulsifier', description: 'Emulsifier that helps mix oil and water. Generally safe in small amounts.', safety: 'safe', uses: ['Ice cream', 'Baked goods'] },
  'e433': { name: 'Polysorbate 80', category: 'Emulsifier', description: 'Emulsifier that helps mix oil and water. Generally safe in small amounts.', safety: 'safe', uses: ['Ice cream', 'Baked goods'] },
  'e434': { name: 'Polysorbate 40', category: 'Emulsifier', description: 'Emulsifier. Generally safe in small amounts.', safety: 'safe' },
  'e435': { name: 'Polysorbate 60', category: 'Emulsifier', description: 'Emulsifier. Generally safe in small amounts.', safety: 'safe' },
  'e436': { name: 'Polysorbate 65', category: 'Emulsifier', description: 'Emulsifier. Generally safe in small amounts.', safety: 'safe' },
  'e440a': { name: 'Pectin', category: 'Thickener / Gelling Agent', description: 'Natural thickener from fruits. Completely safe and high in fiber.', safety: 'safe', uses: ['Jams', 'Jellies', 'Yogurt'] },
  'e440b': { name: 'Amidated Pectin', category: 'Thickener / Gelling Agent', description: 'Modified pectin. Generally safe.', safety: 'safe' },
  'e442': { name: 'Ammonium Phosphatides', category: 'Emulsifier', description: 'Used in chocolate. Generally safe.', safety: 'safe', uses: ['Chocolate'] },
  'e444': { name: 'Sucrose Acetate Isobutyrate', category: 'Emulsifier', description: 'Used in beverages. Generally safe.', safety: 'safe' },
  'e445': { name: 'Glycerol Esters of Wood Rosins', category: 'Emulsifier', description: 'Used in beverages. Generally safe.', safety: 'safe' },
  'e450': { name: 'Diphosphates', category: 'Emulsifier / Acidity Regulator', description: 'Used in processed foods. May cause digestive issues in large amounts.', safety: 'caution', concerns: ['Digestive issues'], uses: ['Processed meats', 'Cheese'] },
  'e451': { name: 'Triphosphates', category: 'Emulsifier / Acidity Regulator', description: 'Used in processed foods. May cause digestive issues in large amounts.', safety: 'caution', concerns: ['Digestive issues'], uses: ['Processed meats'] },
  'e452': { name: 'Polyphosphates', category: 'Emulsifier / Acidity Regulator', description: 'Used in processed foods. May cause digestive issues in large amounts.', safety: 'caution', concerns: ['Digestive issues'], uses: ['Processed meats', 'Seafood'] },
  'e459': { name: 'Beta-Cyclodextrin', category: 'Stabilizer', description: 'Used to encapsulate flavors. Generally safe.', safety: 'safe' },
  'e460': { name: 'Cellulose', category: 'Thickener / Anti-caking', description: 'Natural fiber from plants. Completely safe and high in fiber.', safety: 'safe', uses: ['Shredded cheese', 'Ice cream'] },
  'e461': { name: 'Methylcellulose', category: 'Thickener', description: 'Modified cellulose. Generally safe, but may cause digestive issues in large amounts.', safety: 'caution', concerns: ['Digestive issues'], uses: ['Vegetarian products'] },
  'e463': { name: 'Hydroxypropylcellulose', category: 'Thickener', description: 'Modified cellulose. Generally safe.', safety: 'safe' },
  'e464': { name: 'Hydroxypropyl Methylcellulose', category: 'Thickener', description: 'Modified cellulose. Generally safe.', safety: 'safe' },
  'e465': { name: 'Ethyl Methylcellulose', category: 'Thickener', description: 'Modified cellulose. Generally safe.', safety: 'safe' },
  'e466': { name: 'Carboxymethylcellulose / CMC', category: 'Thickener', description: 'Modified cellulose. Generally safe, but may cause digestive issues in large amounts.', safety: 'caution', concerns: ['Digestive issues'], uses: ['Ice cream', 'Sauces'] },
  'e468': { name: 'Crosslinked Sodium Carboxymethylcellulose', category: 'Thickener', description: 'Modified cellulose. Generally safe.', safety: 'safe' },
  'e469': { name: 'Enzymatically Hydrolyzed Carboxymethylcellulose', category: 'Thickener', description: 'Modified cellulose. Generally safe.', safety: 'safe' },
  'e470a': { name: 'Sodium, Potassium, and Calcium Salts of Fatty Acids', category: 'Emulsifier / Anti-caking', description: 'Salts of natural fatty acids. Generally safe.', safety: 'safe' },
  'e470b': { name: 'Magnesium Salts of Fatty Acids', category: 'Emulsifier / Anti-caking', description: 'Salts of natural fatty acids. Generally safe.', safety: 'safe' },
  'e471': { name: 'Mono- and Diglycerides of Fatty Acids', category: 'Emulsifier', description: 'Common emulsifier from vegetable oils. Generally safe.', safety: 'safe', uses: ['Bread', 'Margarine', 'Ice cream'] },
  'e472a': { name: 'Acetic Acid Esters of Mono- and Diglycerides', category: 'Emulsifier', description: 'Modified emulsifier. Generally safe.', safety: 'safe' },
  'e472b': { name: 'Lactic Acid Esters of Mono- and Diglycerides', category: 'Emulsifier', description: 'Modified emulsifier. Generally safe.', safety: 'safe' },
  'e472c': { name: 'Citric Acid Esters of Mono- and Diglycerides', category: 'Emulsifier', description: 'Modified emulsifier. Generally safe.', safety: 'safe' },
  'e472d': { name: 'Tartaric Acid Esters of Mono- and Diglycerides', category: 'Emulsifier', description: 'Modified emulsifier. Generally safe.', safety: 'safe' },
  'e472e': { name: 'Diacetyltartaric Acid Esters of Mono- and Diglycerides', category: 'Emulsifier', description: 'Modified emulsifier. Generally safe.', safety: 'safe' },
  'e472f': { name: 'Mixed Acetic and Tartaric Acid Esters of Mono- and Diglycerides', category: 'Emulsifier', description: 'Modified emulsifier. Generally safe.', safety: 'safe' },
  'e473': { name: 'Sucrose Esters of Fatty Acids', category: 'Emulsifier', description: 'Emulsifier from sugar and fatty acids. Generally safe.', safety: 'safe', uses: ['Baked goods', 'Dairy products'] },
  'e474': { name: 'Sucroglycerides', category: 'Emulsifier', description: 'Emulsifier from sugar and glycerin. Generally safe.', safety: 'safe' },
  'e475': { name: 'Polyglycerol Esters of Fatty Acids', category: 'Emulsifier', description: 'Emulsifier. Generally safe.', safety: 'safe' },
  'e476': { name: 'Polyglycerol Polyricinoleate', category: 'Emulsifier', description: 'Used in chocolate. Generally safe.', safety: 'safe', uses: ['Chocolate'] },
  'e477': { name: 'Propylene Glycol Esters of Fatty Acids', category: 'Emulsifier', description: 'Emulsifier. Generally safe.', safety: 'safe' },
  'e478': { name: 'Lactylated Fatty Acid Esters of Glycerol and Propylene Glycol', category: 'Emulsifier', description: 'Emulsifier. Generally safe.', safety: 'safe' },
  'e479b': { name: 'Thermally Oxidized Soybean Oil', category: 'Emulsifier', description: 'Used in some foods. Generally safe.', safety: 'safe' },
  'e481': { name: 'Sodium Stearoyl-2-Lactylate', category: 'Emulsifier', description: 'Used in bread. Generally safe.', safety: 'safe', uses: ['Bread', 'Baked goods'] },
  'e482': { name: 'Calcium Stearoyl-2-Lactylate', category: 'Emulsifier', description: 'Used in bread. Generally safe.', safety: 'safe', uses: ['Bread'] },
  'e483': { name: 'Stearyl Tartrate', category: 'Emulsifier', description: 'Used in bread. Generally safe.', safety: 'safe' },
  'e484': { name: 'Stearyl Citrate', category: 'Emulsifier', description: 'Used in some foods. Generally safe.', safety: 'safe' },
  'e485': { name: 'Sodium Stearoyl Fumarate', category: 'Emulsifier', description: 'Used in bread. Generally safe.', safety: 'safe' },
  'e491': { name: 'Sorbitan Monostearate', category: 'Emulsifier', description: 'Emulsifier. Generally safe.', safety: 'safe' },
  'e492': { name: 'Sorbitan Tristearate', category: 'Emulsifier', description: 'Emulsifier. Generally safe.', safety: 'safe' },
  'e493': { name: 'Sorbitan Monolaurate', category: 'Emulsifier', description: 'Emulsifier. Generally safe.', safety: 'safe' },
  'e494': { name: 'Sorbitan Monooleate', category: 'Emulsifier', description: 'Emulsifier. Generally safe.', safety: 'safe' },
  'e495': { name: 'Sorbitan Monopalmitate', category: 'Emulsifier', description: 'Emulsifier. Generally safe.', safety: 'safe' },

  // E500-E599: Acidity Regulators and Anti-caking Agents
  'e500': { name: 'Sodium Carbonate', category: 'Acidity Regulator', description: 'Natural compound used as raising agent. Completely safe.', safety: 'safe', uses: ['Baking powder', 'Noodles'] },
  'e501': { name: 'Potassium Carbonate', category: 'Acidity Regulator', description: 'Used in baking. Generally safe.', safety: 'safe' },
  'e503': { name: 'Ammonium Carbonate', category: 'Acidity Regulator', description: 'Used in baking. Generally safe.', safety: 'safe' },
  'e504': { name: 'Magnesium Carbonate', category: 'Acidity Regulator / Anti-caking', description: 'Used as anti-caking agent. Generally safe.', safety: 'safe', uses: ['Table salt', 'Powdered foods'] },
  'e507': { name: 'Hydrochloric Acid', category: 'Acidity Regulator', description: 'Used in food processing. Generally safe in small amounts.', safety: 'safe' },
  'e508': { name: 'Potassium Chloride', category: 'Acidity Regulator / Salt Substitute', description: 'Used as salt substitute. Generally safe, but may cause digestive issues in large amounts.', safety: 'caution', concerns: ['Digestive issues'], uses: ['Low-sodium products'] },
  'e509': { name: 'Calcium Chloride', category: 'Acidity Regulator / Firming Agent', description: 'Used to firm vegetables and in cheese making. Generally safe.', safety: 'safe', uses: ['Canned vegetables', 'Cheese', 'Tofu'] },
  'e510': { name: 'Ammonium Chloride', category: 'Acidity Regulator', description: 'Used in some foods. Generally safe.', safety: 'safe' },
  'e511': { name: 'Magnesium Chloride', category: 'Acidity Regulator / Firming Agent', description: 'Used in tofu making. Generally safe.', safety: 'safe', uses: ['Tofu'] },
  'e512': { name: 'Stannous Chloride', category: 'Color Retention Agent', description: 'Used in some foods. Generally safe.', safety: 'safe' },
  'e513': { name: 'Sulfuric Acid', category: 'Acidity Regulator', description: 'Used in food processing. Generally safe in small amounts.', safety: 'safe' },
  'e514': { name: 'Sodium Sulfate', category: 'Acidity Regulator', description: 'Used in some foods. Generally safe.', safety: 'safe' },
  'e515': { name: 'Potassium Sulfate', category: 'Acidity Regulator', description: 'Used in some foods. Generally safe.', safety: 'safe' },
  'e516': { name: 'Calcium Sulfate', category: 'Acidity Regulator / Firming Agent', description: 'Used in tofu making and as firming agent. Generally safe.', safety: 'safe', uses: ['Tofu', 'Baked goods'] },
  'e517': { name: 'Ammonium Sulfate', category: 'Acidity Regulator', description: 'Used in some foods. Generally safe.', safety: 'safe' },
  'e520': { name: 'Aluminium Sulfate', category: 'Firming Agent', description: 'Used in some foods. May accumulate in body. Use with caution.', safety: 'caution', concerns: ['May accumulate in body'] },
  'e521': { name: 'Aluminium Sodium Sulfate', category: 'Firming Agent', description: 'May accumulate in body. Use with caution.', safety: 'caution', concerns: ['May accumulate in body'] },
  'e522': { name: 'Aluminium Potassium Sulfate', category: 'Firming Agent', description: 'May accumulate in body. Use with caution.', safety: 'caution', concerns: ['May accumulate in body'] },
  'e523': { name: 'Aluminium Ammonium Sulfate', category: 'Firming Agent', description: 'May accumulate in body. Use with caution.', safety: 'caution', concerns: ['May accumulate in body'] },
  'e524': { name: 'Sodium Hydroxide', category: 'Acidity Regulator', description: 'Used in food processing (lye). Generally safe in processed foods.', safety: 'safe', uses: ['Pretzels', 'Olives'] },
  'e525': { name: 'Potassium Hydroxide', category: 'Acidity Regulator', description: 'Used in food processing. Generally safe in processed foods.', safety: 'safe' },
  'e526': { name: 'Calcium Hydroxide', category: 'Acidity Regulator', description: 'Used in food processing. Generally safe.', safety: 'safe', uses: ['Corn products'] },
  'e527': { name: 'Ammonium Hydroxide', category: 'Acidity Regulator', description: 'Used in food processing. Generally safe.', safety: 'safe' },
  'e528': { name: 'Magnesium Hydroxide', category: 'Acidity Regulator', description: 'Used as antacid. Generally safe.', safety: 'safe' },
  'e529': { name: 'Calcium Oxide', category: 'Acidity Regulator', description: 'Used in food processing. Generally safe.', safety: 'safe' },
  'e530': { name: 'Magnesium Oxide', category: 'Acidity Regulator / Anti-caking', description: 'Used as anti-caking agent and magnesium supplement. Generally safe.', safety: 'safe', uses: ['Table salt', 'Powdered foods'] },
  'e535': { name: 'Sodium Ferrocyanide', category: 'Anti-caking Agent', description: 'Used in table salt. Generally safe in small amounts.', safety: 'safe', uses: ['Table salt'] },
  'e536': { name: 'Potassium Ferrocyanide', category: 'Anti-caking Agent', description: 'Used in table salt. Generally safe in small amounts.', safety: 'safe', uses: ['Table salt'] },
  'e538': { name: 'Calcium Ferrocyanide', category: 'Anti-caking Agent', description: 'Used in table salt. Generally safe in small amounts.', safety: 'safe', uses: ['Table salt'] },
  'e540': { name: 'Dicalcium Diphosphate', category: 'Acidity Regulator', description: 'Used in baking powder. Generally safe.', safety: 'safe' },
  'e541': { name: 'Sodium Aluminium Phosphate', category: 'Acidity Regulator', description: 'Used in baking powder. May accumulate in body. Use with caution.', safety: 'caution', concerns: ['May accumulate in body'], uses: ['Baking powder'] },
  'e542': { name: 'Bone Phosphate', category: 'Anti-caking Agent', description: 'Made from animal bones. Not suitable for vegetarians. Generally safe otherwise.', safety: 'caution', concerns: ['Not vegetarian'], uses: ['Table salt'] },
  'e544': { name: 'Calcium Polyphosphates', category: 'Emulsifier', description: 'Used in processed foods. Generally safe.', safety: 'safe' },
  'e545': { name: 'Ammonium Polyphosphates', category: 'Emulsifier', description: 'Used in processed foods. Generally safe.', safety: 'safe' },
  'e550': { name: 'Sodium Silicate', category: 'Anti-caking Agent', description: 'Used in some foods. Generally safe.', safety: 'safe' },
  'e551': { name: 'Silicon Dioxide', category: 'Anti-caking Agent', description: 'Natural anti-caking agent (silica/sand). Prevents clumping. Completely safe and inert.', safety: 'safe', uses: ['Table salt', 'Powdered foods', 'Spices'] },
  'e552': { name: 'Calcium Silicate', category: 'Anti-caking Agent', description: 'Used to prevent clumping. Generally safe.', safety: 'safe', uses: ['Table salt', 'Powdered foods'] },
  'e553a': { name: 'Magnesium Silicate / Talc', category: 'Anti-caking Agent', description: 'Used to prevent clumping. Generally safe in small amounts.', safety: 'safe', uses: ['Rice', 'Table salt'] },
  'e553b': { name: 'Talc', category: 'Anti-caking Agent', description: 'Used to prevent clumping. Generally safe in small amounts.', safety: 'safe' },
  'e554': { name: 'Sodium Aluminium Silicate', category: 'Anti-caking Agent', description: 'May accumulate in body. Use with caution.', safety: 'caution', concerns: ['May accumulate in body'], uses: ['Table salt'] },
  'e555': { name: 'Potassium Aluminium Silicate', category: 'Anti-caking Agent', description: 'May accumulate in body. Use with caution.', safety: 'caution', concerns: ['May accumulate in body'] },
  'e556': { name: 'Calcium Aluminium Silicate', category: 'Anti-caking Agent', description: 'May accumulate in body. Use with caution.', safety: 'caution', concerns: ['May accumulate in body'] },
  'e558': { name: 'Bentonite', category: 'Anti-caking Agent', description: 'Natural clay. Generally safe.', safety: 'safe' },
  'e559': { name: 'Aluminium Silicate / Kaolin', category: 'Anti-caking Agent', description: 'Natural clay. May accumulate in body. Use with caution.', safety: 'caution', concerns: ['May accumulate in body'] },
  'e570': { name: 'Stearic Acid', category: 'Anti-foaming Agent', description: 'Natural fatty acid. Generally safe.', safety: 'safe' },
  'e574': { name: 'Gluconic Acid', category: 'Acidity Regulator', description: 'Natural acid. Generally safe.', safety: 'safe' },
  'e575': { name: 'Glucono Delta-Lactone', category: 'Acidity Regulator', description: 'Natural compound. Generally safe.', safety: 'safe' },
  'e576': { name: 'Sodium Gluconate', category: 'Acidity Regulator', description: 'Sodium salt of gluconic acid. Generally safe.', safety: 'safe' },
  'e577': { name: 'Potassium Gluconate', category: 'Acidity Regulator', description: 'Potassium salt of gluconic acid. Generally safe.', safety: 'safe' },
  'e578': { name: 'Calcium Gluconate', category: 'Acidity Regulator', description: 'Calcium salt of gluconic acid. Generally safe.', safety: 'safe' },
  'e579': { name: 'Ferrous Gluconate', category: 'Color Retention Agent', description: 'Iron supplement and color agent. Generally safe.', safety: 'safe' },
  'e585': { name: 'Ferrous Lactate', category: 'Color Retention Agent', description: 'Iron supplement and color agent. Generally safe.', safety: 'safe' },

  // E600-E699: Flavor Enhancers
  'e620': { name: 'Glutamic Acid', category: 'Flavor Enhancer', description: 'Natural amino acid that enhances flavor. Generally safe.', safety: 'safe' },
  'e621': { name: 'Monosodium Glutamate (MSG)', category: 'Flavor Enhancer', description: 'Enhances savory flavor (umami). Some people may be sensitive, causing headaches, nausea, or flushing. Generally safe for most people.', safety: 'caution', concerns: ['Headaches in sensitive individuals', 'Nausea', 'Flushing'], uses: ['Soups', 'Processed foods', 'Chinese food'] },
  'e622': { name: 'Monopotassium Glutamate', category: 'Flavor Enhancer', description: 'Similar to MSG. Generally safe for most people.', safety: 'caution', concerns: ['Headaches in sensitive individuals'] },
  'e623': { name: 'Calcium Diglutamate', category: 'Flavor Enhancer', description: 'Similar to MSG. Generally safe for most people.', safety: 'caution', concerns: ['Headaches in sensitive individuals'] },
  'e624': { name: 'Monoammonium Glutamate', category: 'Flavor Enhancer', description: 'Similar to MSG. Generally safe for most people.', safety: 'caution', concerns: ['Headaches in sensitive individuals'] },
  'e625': { name: 'Magnesium Diglutamate', category: 'Flavor Enhancer', description: 'Similar to MSG. Generally safe for most people.', safety: 'caution', concerns: ['Headaches in sensitive individuals'] },
  'e626': { name: 'Guanylic Acid', category: 'Flavor Enhancer', description: 'Enhances flavor. Generally safe.', safety: 'safe' },
  'e627': { name: 'Disodium Guanylate', category: 'Flavor Enhancer', description: 'Enhances savory flavor. Often used with MSG. Generally safe.', safety: 'safe', uses: ['Processed foods', 'Snacks'] },
  'e628': { name: 'Dipotassium Guanylate', category: 'Flavor Enhancer', description: 'Enhances flavor. Generally safe.', safety: 'safe' },
  'e629': { name: 'Calcium Guanylate', category: 'Flavor Enhancer', description: 'Enhances flavor. Generally safe.', safety: 'safe' },
  'e630': { name: 'Inosinic Acid', category: 'Flavor Enhancer', description: 'Enhances flavor. Generally safe.', safety: 'safe' },
  'e631': { name: 'Disodium Inosinate', category: 'Flavor Enhancer', description: 'Enhances savory flavor. Often used with MSG. Generally safe.', safety: 'safe', uses: ['Processed foods', 'Snacks'] },
  'e632': { name: 'Dipotassium Inosinate', category: 'Flavor Enhancer', description: 'Enhances flavor. Generally safe.', safety: 'safe' },
  'e633': { name: 'Calcium Inosinate', category: 'Flavor Enhancer', description: 'Enhances flavor. Generally safe.', safety: 'safe' },
  'e634': { name: 'Calcium 5\'-Ribonucleotides', category: 'Flavor Enhancer', description: 'Enhances flavor. Generally safe.', safety: 'safe' },
  'e635': { name: 'Disodium 5\'-Ribonucleotides', category: 'Flavor Enhancer', description: 'Enhances savory flavor combination. Generally safe.', safety: 'safe', uses: ['Processed foods', 'Snacks'] },
  'e640': { name: 'Glycine', category: 'Flavor Enhancer', description: 'Natural amino acid. Completely safe.', safety: 'safe' },
  'e641': { name: 'L-Leucine', category: 'Flavor Enhancer', description: 'Natural amino acid. Completely safe.', safety: 'safe' },
  'e650': { name: 'Zinc Acetate', category: 'Flavor Enhancer', description: 'Used in some foods. Generally safe.', safety: 'safe' },

  // E700-E799: Antibiotics (not used in food)
  // E900-E999: Glazing Agents, Sweeteners, and Others
  'e900': { name: 'Dimethylpolysiloxane', category: 'Anti-foaming Agent', description: 'Prevents foam formation in cooking oils. Generally considered safe.', safety: 'safe', uses: ['Cooking oils', 'Deep-fried foods'] },
  'e901': { name: 'Beeswax', category: 'Glazing Agent', description: 'Natural wax from bees. Completely safe. Not suitable for vegans.', safety: 'safe', uses: ['Candies', 'Fruits'], concerns: ['Not vegan'] },
  'e902': { name: 'Candelilla Wax', category: 'Glazing Agent', description: 'Natural wax from plants. Completely safe and vegan.', safety: 'safe', uses: ['Candies', 'Fruits'] },
  'e903': { name: 'Carnauba Wax', category: 'Glazing Agent', description: 'Natural wax from carnauba palm. Completely safe and vegan.', safety: 'safe', uses: ['Candies', 'Fruits', 'Chocolate'] },
  'e904': { name: 'Shellac', category: 'Glazing Agent', description: 'Natural resin from lac bugs. Not suitable for vegetarians/vegans. Generally safe otherwise.', safety: 'safe', uses: ['Candies', 'Fruits'], concerns: ['Not vegetarian'] },
  'e905': { name: 'Microcrystalline Wax', category: 'Glazing Agent', description: 'Petroleum-based wax. Generally safe in small amounts.', safety: 'safe' },
  'e907': { name: 'Refined Microcrystalline Wax', category: 'Glazing Agent', description: 'Refined petroleum wax. Generally safe in small amounts.', safety: 'safe' },
  'e912': { name: 'Montan Acid Esters', category: 'Glazing Agent', description: 'Wax from lignite. Generally safe.', safety: 'safe' },
  'e914': { name: 'Oxidized Polyethylene Wax', category: 'Glazing Agent', description: 'Synthetic wax. Generally safe in small amounts.', safety: 'safe' },
  'e920': { name: 'L-Cysteine', category: 'Flour Treatment Agent', description: 'Amino acid used in bread making. Often derived from human hair or duck feathers. May not be suitable for some dietary restrictions.', safety: 'caution', concerns: ['Source may be animal-derived'], uses: ['Bread', 'Baked goods'] },
  'e921': { name: 'L-Cystine', category: 'Flour Treatment Agent', description: 'Amino acid used in bread making. Similar concerns to L-cysteine.', safety: 'caution', concerns: ['Source may be animal-derived'] },
  'e924': { name: 'Potassium Bromate', category: 'Flour Treatment Agent', description: 'Used in bread making. Banned in EU and many countries due to potential carcinogenicity.', safety: 'avoid', concerns: ['Potential carcinogen', 'Banned in EU'], uses: ['Bread'] },
  'e925': { name: 'Chlorine', category: 'Flour Treatment Agent', description: 'Used to bleach flour. Generally safe in processed foods.', safety: 'safe' },
  'e926': { name: 'Chlorine Dioxide', category: 'Flour Treatment Agent', description: 'Used to bleach flour. Generally safe in processed foods.', safety: 'safe' },
  'e927a': { name: 'Azodicarbonamide', category: 'Flour Treatment Agent', description: 'Used in bread making. Banned in EU due to potential health concerns.', safety: 'avoid', concerns: ['Banned in EU'], uses: ['Bread'] },
  'e927b': { name: 'Carbamide', category: 'Flour Treatment Agent', description: 'Used in some foods. Generally safe.', safety: 'safe' },
  'e928': { name: 'Benzoyl Peroxide', category: 'Flour Treatment Agent', description: 'Used to bleach flour. Generally safe in processed foods.', safety: 'safe' },
  'e930': { name: 'Calcium Peroxide', category: 'Flour Treatment Agent', description: 'Used in bread making. Generally safe.', safety: 'safe' },
  'e938': { name: 'Argon', category: 'Packaging Gas', description: 'Inert gas used in packaging. Completely safe.', safety: 'safe' },
  'e939': { name: 'Helium', category: 'Packaging Gas', description: 'Inert gas used in packaging. Completely safe.', safety: 'safe' },
  'e941': { name: 'Nitrogen', category: 'Packaging Gas', description: 'Inert gas used in packaging. Completely safe.', safety: 'safe', uses: ['Packaged foods'] },
  'e942': { name: 'Nitrous Oxide', category: 'Packaging Gas / Propellant', description: 'Used in whipped cream. Generally safe.', safety: 'safe', uses: ['Whipped cream'] },
  'e943a': { name: 'Butane', category: 'Propellant', description: 'Used as propellant. Generally safe in small amounts.', safety: 'safe' },
  'e943b': { name: 'Isobutane', category: 'Propellant', description: 'Used as propellant. Generally safe in small amounts.', safety: 'safe' },
  'e944': { name: 'Propane', category: 'Propellant', description: 'Used as propellant. Generally safe in small amounts.', safety: 'safe' },
  'e948': { name: 'Oxygen', category: 'Packaging Gas', description: 'Used in packaging. Completely safe.', safety: 'safe' },
  'e949': { name: 'Hydrogen', category: 'Packaging Gas', description: 'Used in packaging. Completely safe.', safety: 'safe' },
  'e950': { name: 'Acesulfame K / Acesulfame Potassium', category: 'Sweetener', description: 'Artificial sweetener. 200 times sweeter than sugar. Generally safe, but some studies suggest potential concerns.', safety: 'safe', uses: ['Diet drinks', 'Sugar-free products'] },
  'e951': { name: 'Aspartame', category: 'Sweetener', description: 'Artificial sweetener. Safe for most people, but avoid if you have phenylketonuria (PKU). May cause headaches in sensitive individuals.', safety: 'caution', concerns: ['Avoid if PKU', 'Headaches in sensitive individuals'], uses: ['Diet drinks', 'Sugar-free products'] },
  'e952': { name: 'Cyclamic Acid / Cyclamate', category: 'Sweetener', description: 'Artificial sweetener. Banned in US due to potential carcinogenicity concerns. Still used in some countries.', safety: 'caution', concerns: ['Banned in US', 'Potential carcinogen'], uses: ['Diet drinks'] },
  'e953': { name: 'Isomalt', category: 'Sweetener', description: 'Sugar alcohol. May cause digestive issues in large amounts.', safety: 'caution', concerns: ['Digestive issues'], uses: ['Sugar-free products'] },
  'e954': { name: 'Saccharin', category: 'Sweetener', description: 'Artificial sweetener. 300-400 times sweeter than sugar. Generally safe, though some studies suggest potential concerns.', safety: 'safe', uses: ['Diet drinks', 'Sugar-free products'] },
  'e955': { name: 'Sucralose', category: 'Sweetener', description: 'Artificial sweetener derived from sugar. 600 times sweeter than sugar. Generally considered safe.', safety: 'safe', uses: ['Diet drinks', 'Sugar-free products', 'Baked goods'] },
  'e956': { name: 'Alitame', category: 'Sweetener', description: 'Artificial sweetener. Generally safe.', safety: 'safe' },
  'e957': { name: 'Thaumatin', category: 'Sweetener / Flavor Enhancer', description: 'Natural sweetener from katemfe fruit. 2000-3000 times sweeter than sugar. Completely safe.', safety: 'safe', uses: ['Desserts', 'Beverages'] },
  'e958': { name: 'Glycyrrhizin', category: 'Sweetener / Flavor Enhancer', description: 'Natural sweetener from licorice root. May cause high blood pressure in large amounts.', safety: 'caution', concerns: ['High blood pressure'], uses: ['Candies', 'Beverages'] },
  'e959': { name: 'Neohesperidin Dihydrochalcone', category: 'Sweetener', description: 'Natural sweetener from citrus. Generally safe.', safety: 'safe' },
  'e960': { name: 'Steviol Glycosides (Stevia)', category: 'Sweetener', description: 'Natural sweetener from stevia plant. 200-300 times sweeter than sugar. Completely safe and may have health benefits.', safety: 'safe', uses: ['Diet drinks', 'Sugar-free products', 'Natural sweeteners'] },
  'e961': { name: 'Neotame', category: 'Sweetener', description: 'Artificial sweetener. 7000-13000 times sweeter than sugar. Generally safe.', safety: 'safe' },
  'e962': { name: 'Salt of Aspartame-Acesulfame', category: 'Sweetener', description: 'Combination of aspartame and acesulfame. Similar concerns to aspartame.', safety: 'caution', concerns: ['Avoid if PKU'] },
  'e965': { name: 'Maltitol', category: 'Sweetener', description: 'Sugar alcohol. May cause digestive issues in large amounts.', safety: 'caution', concerns: ['Digestive issues'], uses: ['Sugar-free products'] },
  'e966': { name: 'Lactitol', category: 'Sweetener', description: 'Sugar alcohol. May cause digestive issues in large amounts.', safety: 'caution', concerns: ['Digestive issues'], uses: ['Sugar-free products'] },
  'e967': { name: 'Xylitol', category: 'Sweetener', description: 'Natural sugar alcohol from birch trees. Safe for humans but toxic to dogs. May cause digestive issues in large amounts. Helps prevent tooth decay.', safety: 'caution', concerns: ['Toxic to dogs', 'Digestive issues'], uses: ['Chewing gum', 'Sugar-free products'] },
  'e968': { name: 'Erythritol', category: 'Sweetener', description: 'Sugar alcohol. Generally well-tolerated with fewer digestive issues than other sugar alcohols.', safety: 'safe', uses: ['Sugar-free products', 'Low-calorie foods'] },
  'e999': { name: 'Quillaia Extract', category: 'Foaming Agent', description: 'Natural foaming agent from quillaia tree bark. Generally safe in small amounts.', safety: 'safe', uses: ['Root beer', 'Beverages'] },
  'e1200': { name: 'Polydextrose', category: 'Bulking Agent', description: 'Synthetic fiber. May cause digestive issues in large amounts.', safety: 'caution', concerns: ['Digestive issues'], uses: ['Sugar-free products'] },
  'e1201': { name: 'Polyvinylpyrrolidone', category: 'Stabilizer', description: 'Used in some foods. Generally safe.', safety: 'safe' },
  'e1202': { name: 'Polyvinylpolypyrrolidone', category: 'Stabilizer', description: 'Used in wine and beer clarification. Generally safe.', safety: 'safe', uses: ['Wine', 'Beer'] },
  'e1203': { name: 'Polyvinyl Alcohol', category: 'Coating Agent', description: 'Used as coating. Generally safe.', safety: 'safe' },
  'e1204': { name: 'Pullulan', category: 'Thickener', description: 'Natural thickener from fermentation. Generally safe.', safety: 'safe' },
  'e1400': { name: 'Dextrin', category: 'Thickener', description: 'Natural thickener from starch. Generally safe.', safety: 'safe' },
  'e1401': { name: 'Acid-Treated Starch', category: 'Thickener', description: 'Modified starch. Generally safe.', safety: 'safe' },
  'e1402': { name: 'Alkaline Treated Starch', category: 'Thickener', description: 'Modified starch. Generally safe.', safety: 'safe' },
  'e1403': { name: 'Bleached Starch', category: 'Thickener', description: 'Modified starch. Generally safe.', safety: 'safe' },
  'e1404': { name: 'Oxidized Starch', category: 'Thickener', description: 'Modified starch. Generally safe.', safety: 'safe' },
  'e1405': { name: 'Enzyme-Treated Starch', category: 'Thickener', description: 'Modified starch. Generally safe.', safety: 'safe' },
  'e1410': { name: 'Monostarch Phosphate', category: 'Thickener', description: 'Modified starch. Generally safe.', safety: 'safe' },
  'e1412': { name: 'Distarch Phosphate', category: 'Thickener', description: 'Modified starch. Generally safe.', safety: 'safe' },
  'e1413': { name: 'Phosphated Distarch Phosphate', category: 'Thickener', description: 'Modified starch. Generally safe.', safety: 'safe' },
  'e1414': { name: 'Acetylated Distarch Phosphate', category: 'Thickener', description: 'Modified starch. Generally safe.', safety: 'safe' },
  'e1420': { name: 'Acetylated Starch', category: 'Thickener', description: 'Modified starch. Generally safe.', safety: 'safe' },
  'e1422': { name: 'Acetylated Distarch Adipate', category: 'Thickener', description: 'Modified starch. Generally safe.', safety: 'safe' },
  'e1440': { name: 'Hydroxypropyl Starch', category: 'Thickener', description: 'Modified starch. Generally safe.', safety: 'safe' },
  'e1442': { name: 'Hydroxypropyl Distarch Phosphate', category: 'Thickener', description: 'Modified starch. Generally safe.', safety: 'safe' },
  'e1450': { name: 'Starch Sodium Octenyl Succinate', category: 'Thickener / Emulsifier', description: 'Modified starch. Generally safe.', safety: 'safe' },
  'e1451': { name: 'Acetylated Oxidized Starch', category: 'Thickener', description: 'Modified starch. Generally safe.', safety: 'safe' },
  'e1452': { name: 'Starch Aluminium Octenyl Succinate', category: 'Thickener / Emulsifier', description: 'Modified starch. May accumulate in body. Use with caution.', safety: 'caution', concerns: ['May accumulate in body'] },
  'e1505': { name: 'Triethyl Citrate', category: 'Foaming Agent', description: 'Used in some foods. Generally safe.', safety: 'safe' },
  'e1518': { name: 'Triacetin', category: 'Humectant', description: 'Used in some foods. Generally safe.', safety: 'safe' },
  'e1520': { name: 'Propylene Glycol', category: 'Humectant / Solvent', description: 'Used in some foods and cosmetics. Generally safe in small amounts, but may cause allergic reactions.', safety: 'caution', concerns: ['Allergic reactions'], uses: ['Processed foods', 'Cosmetics'] },
  'e1521': { name: 'Polyethylene Glycol', category: 'Humectant', description: 'Used in some foods. Generally safe in small amounts.', safety: 'safe' },
};

/**
 * Get comprehensive information about an E-number additive
 */
export function getAdditiveInfo(eNumber: string): AdditiveInfo | null {
  const key = eNumber.toLowerCase().replace(/\s+/g, '');
  return ADDITIVE_DATABASE[key] || null;
}

/**
 * Check if an E-number exists in the database
 */
export function hasAdditiveInfo(eNumber: string): boolean {
  const key = eNumber.toLowerCase().replace(/\s+/g, '');
  return key in ADDITIVE_DATABASE;
}

