import type { ClaimDefinition } from './types';

/**
 * Subset of `docs/phase2/claim-registry.csv` with `enI18nPath` for automated EN drift tests.
 * Keep claimIds aligned with registry rows when possible.
 */
export const CLAIM_DEFINITIONS: readonly ClaimDefinition[] = [
  {
    claimId: 'onb-welcome-title',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'onboarding.title',
    mustNotSay: ['TrueScan', 'TruScore', 'guaranteed'],
    approvedAnchors: ['rveel'],
    surfaceLocation: 'Onboarding welcome',
    dependentCodePath: 'app/onboarding.tsx',
    owner: 'Product',
    status: 'approved',
    lastReviewedDate: '2026-04-14',
  },
  {
    claimId: 'onb-slide1-title',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'onboarding.slide1.title',
    mustNotSay: ['proven', 'verified safe'],
    approvedAnchors: ['transparency'],
    surfaceLocation: 'Onboarding slide 1',
    dependentCodePath: 'app/onboarding.tsx',
    owner: 'Product',
    status: 'approved',
    lastReviewedDate: '2026-04-14',
  },
  {
    claimId: 'onb-slide2-title',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'onboarding.slide2.title',
    mustNotSay: ['TrueScan', 'TruScore'],
    approvedAnchors: ['rveel score'],
    surfaceLocation: 'Onboarding slide 2',
    dependentCodePath: 'app/onboarding.tsx',
    owner: 'Product',
    status: 'draft',
    lastReviewedDate: '2026-04-14',
  },
  {
    claimId: 'onb-slide3-title',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'onboarding.slide3.title',
    mustNotSay: ['TrueScan'],
    approvedAnchors: ['privacy'],
    surfaceLocation: 'Onboarding slide 3',
    dependentCodePath: 'app/onboarding.tsx',
    owner: 'Legal/Compliance',
    status: 'approved',
    lastReviewedDate: '2026-04-14',
  },
  {
    claimId: 'legal-disclaimer-p1',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'result.legalDisclaimerModalP1',
    mustNotSay: ['fda approved', 'miracle cure', 'guaranteed cure', 'replace your doctor'],
    approvedAnchors: ['rveel', 'does not provide medical advice'],
    surfaceLocation: 'Result disclaimer modal §1',
    dependentCodePath: 'src/components/productLegal/ProductDisclaimerCard.tsx',
    owner: 'Legal/Compliance',
    status: 'approved',
    lastReviewedDate: '2026-04-14',
  },
  {
    claimId: 'legal-disclaimer-p2',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'result.legalDisclaimerModalP2',
    mustNotSay: ['guaranteed accuracy', 'always correct', 'fda approved'],
    approvedAnchors: ['rveel score', 'informational'],
    surfaceLocation: 'Result disclaimer modal §2',
    dependentCodePath: 'src/components/productLegal/ProductDisclaimerCard.tsx',
    owner: 'Legal/Compliance',
    status: 'approved',
    lastReviewedDate: '2026-04-14',
  },
  {
    claimId: 'legal-disclaimer-p3',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'result.legalDisclaimerModalP3',
    mustNotSay: ['ignore the label', 'replace the label'],
    approvedAnchors: ['authoritative', 'official product label'],
    surfaceLocation: 'Result disclaimer modal §3',
    dependentCodePath: 'src/components/productLegal/ProductDisclaimerCard.tsx',
    owner: 'Legal/Compliance',
    status: 'approved',
    lastReviewedDate: '2026-04-14',
  },
  {
    claimId: 'legal-disclaimer-p4',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'result.legalDisclaimerModalP4',
    mustNotSay: ['fda cleared device', 'guaranteed accuracy'],
    approvedAnchors: ['no warranty', 'rveel'],
    surfaceLocation: 'Result disclaimer modal §4',
    dependentCodePath: 'src/components/productLegal/ProductDisclaimerCard.tsx',
    owner: 'Legal/Compliance',
    status: 'approved',
    lastReviewedDate: '2026-04-14',
  },
  {
    claimId: 'legal-disclaimer-p5',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'result.legalDisclaimerModalP5',
    mustNotSay: ['guaranteed', 'warranty of merchantability'],
    approvedAnchors: ['disclaims all liability', 'rveel'],
    surfaceLocation: 'Result disclaimer modal §5',
    dependentCodePath: 'src/components/productLegal/ProductDisclaimerCard.tsx',
    owner: 'Legal/Compliance',
    status: 'approved',
    lastReviewedDate: '2026-04-14',
  },
  {
    claimId: 'legal-disclaimer-p6',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'result.legalDisclaimerModalP6',
    mustNotSay: ['doctor-patient relationship', 'hipaa certified'],
    approvedAnchors: ['own risk', 'rveel'],
    surfaceLocation: 'Result disclaimer modal §6',
    dependentCodePath: 'src/components/productLegal/ProductDisclaimerCard.tsx',
    owner: 'Legal/Compliance',
    status: 'approved',
    lastReviewedDate: '2026-04-14',
  },
  {
    claimId: 'legal-disclaimer-p7',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'result.legalDisclaimerModalP7',
    mustNotSay: ['guaranteed safe for allergies'],
    approvedAnchors: ['qualified professional', 'allergies'],
    surfaceLocation: 'Result disclaimer modal §7',
    dependentCodePath: 'src/components/productLegal/ProductDisclaimerCard.tsx',
    owner: 'Legal/Compliance',
    status: 'approved',
    lastReviewedDate: '2026-04-14',
  },
  {
    claimId: 'legal-data-limits-p1',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'result.legalDataLimitationsModalP1',
    mustNotSay: ['100% complete', 'always accurate'],
    approvedAnchors: ['crowd-sourced', 'errors'],
    surfaceLocation: 'Result data limitations §1',
    dependentCodePath: 'src/components/productLegal/ProductDisclaimerCard.tsx',
    owner: 'Legal/Compliance',
    status: 'approved',
    lastReviewedDate: '2026-04-14',
  },
  {
    claimId: 'legal-data-limits-p2',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'result.legalDataLimitationsModalP2',
    mustNotSay: ['safe for you', 'unsafe for you'],
    approvedAnchors: ['informational only', 'do not assert'],
    surfaceLocation: 'Result data limitations §2',
    dependentCodePath: 'src/components/productLegal/ProductDisclaimerCard.tsx',
    owner: 'Legal/Compliance',
    status: 'approved',
    lastReviewedDate: '2026-04-14',
  },
  {
    claimId: 'legal-data-limits-p3',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'result.legalDataLimitationsModalP3',
    mustNotSay: ['free of all allergens'],
    approvedAnchors: ['does not mean', 'allergens'],
    surfaceLocation: 'Result data limitations §3',
    dependentCodePath: 'src/components/productLegal/ProductDisclaimerCard.tsx',
    owner: 'Legal/Compliance',
    status: 'approved',
    lastReviewedDate: '2026-04-14',
  },
  {
    claimId: 'legal-data-limits-p4',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'result.legalDataLimitationsModalP4',
    mustNotSay: ['money-back guarantee', 'fda approved listing'],
    approvedAnchors: ['does not warrant', 'physical product label'],
    surfaceLocation: 'Result data limitations §4',
    dependentCodePath: 'src/components/productLegal/ProductDisclaimerCard.tsx',
    owner: 'Legal/Compliance',
    status: 'approved',
    lastReviewedDate: '2026-04-14',
  },
  {
    claimId: 'legal-data-limits-p5',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'result.legalDataLimitationsModalP5',
    mustNotSay: ['guaranteed'],
    approvedAnchors: ['disclaims liability'],
    surfaceLocation: 'Result data limitations §5',
    dependentCodePath: 'src/components/productLegal/ProductDisclaimerCard.tsx',
    owner: 'Legal/Compliance',
    status: 'approved',
    lastReviewedDate: '2026-04-14',
  },
  {
    claimId: 'method-info-modal-note',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'infoModal.trustScore.note',
    mustNotSay: ['secret algorithm', '100% accurate'],
    approvedAnchors: ['rveel score', 'open food facts'],
    surfaceLocation: 'Rveel Score info modal note',
    dependentCodePath: 'src/components/TrustScoreInfoModal.tsx',
    owner: 'Data/Methodology',
    status: 'draft',
    lastReviewedDate: '2026-04-14',
  },
  {
    claimId: 'method-info-modal-description',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'infoModal.trustScore.description',
    mustNotSay: ['TrueScan', 'TruScore'],
    approvedAnchors: ['rveel score', 'recognized public systems'],
    surfaceLocation: 'Rveel Score info modal description',
    dependentCodePath: 'src/components/TrustScoreInfoModal.tsx',
    owner: 'Data/Methodology',
    status: 'draft',
    lastReviewedDate: '2026-04-14',
  },
  {
    claimId: 'method-info-modal-formula',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'infoModal.trustScore.formula',
    mustNotSay: ['TrueScan', 'TruScore'],
    approvedAnchors: ['rveel score', 'body'],
    surfaceLocation: 'Rveel Score info modal formula',
    dependentCodePath: 'src/components/TrustScoreInfoModal.tsx',
    owner: 'Data/Methodology',
    status: 'draft',
    lastReviewedDate: '2026-04-14',
  },
  {
    claimId: 'share-burn-prefill',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'nutrition.burnSharePrefill',
    mustNotSay: ['prescription drug', 'guaranteed weight loss', 'cures obesity', 'treats your condition'],
    approvedAnchors: ['not medical advice', 'comparison only'],
    surfaceLocation: 'Nutrition burn share prefill',
    dependentCodePath: 'src/utils/nutritionShareCopy.ts;src/features/sharing/services/ShareContentBuilder.ts',
    owner: 'Legal/Compliance',
    status: 'approved',
    lastReviewedDate: '2026-04-14',
  },
  {
    claimId: 'paywall-subscription-subtitle',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'subscription.subtitle',
    mustNotSay: ['guaranteed', 'TrueScan'],
    approvedAnchors: ['premium', 'unlock'],
    surfaceLocation: 'Subscription screen subtitle',
    dependentCodePath: 'app/subscription.tsx',
    owner: 'Product',
    status: 'approved',
    lastReviewedDate: '2026-04-14',
  },
  {
    claimId: 'paywall-search-body',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'search.paywall.body',
    mustNotSay: ['guaranteed results', 'medical advice'],
    approvedAnchors: ['nutrition', 'eco'],
    surfaceLocation: 'Search paywall body',
    dependentCodePath: 'app/search.tsx',
    owner: 'Product',
    status: 'draft',
    lastReviewedDate: '2026-04-14',
  },
  {
    claimId: 'scan-screen-title',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'scan.title',
    mustNotSay: ['TrueScan', 'TruScore'],
    approvedAnchors: ['rveel'],
    surfaceLocation: 'Scan tab title',
    dependentCodePath: 'app/(tabs)',
    owner: 'Product',
    status: 'approved',
    lastReviewedDate: '2026-04-14',
  },
  {
    claimId: 'score-insufficient-data',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'result.insufficientDataMessage',
    mustNotSay: ['TrueScan', 'TruScore'],
    approvedAnchors: ['rveel score', 'open food facts'],
    surfaceLocation: 'Result insufficient data message',
    dependentCodePath: 'app/result/*',
    owner: 'Data/Methodology',
    status: 'draft',
    lastReviewedDate: '2026-04-14',
  },
  {
    claimId: 'settings-methodology-label',
    claimClass: 'C_app_native_interpretation',
    enI18nPath: 'settings.methodology',
    mustNotSay: ['TrueScan', 'TruScore'],
    approvedAnchors: ['rveel score'],
    surfaceLocation: 'Settings methodology row',
    dependentCodePath: 'app/settings.tsx',
    owner: 'Product',
    status: 'approved',
    lastReviewedDate: '2026-04-14',
  },
];
