/** Flag glyph for a country name. Unknown countries use a globe. */
const COUNTRY_FLAGS: Record<string, string> = {
  USA: '🇺🇸',
  'UNITED STATES': '🇺🇸',
  CANADA: '🇨🇦',
  MEXICO: '🇲🇽',
  UK: '🇬🇧',
  'UNITED KINGDOM': '🇬🇧',
  FRANCE: '🇫🇷',
  GERMANY: '🇩🇪',
  ITALY: '🇮🇹',
  SPAIN: '🇪🇸',
  NETHERLANDS: '🇳🇱',
  BELGIUM: '🇧🇪',
  SWITZERLAND: '🇨🇭',
  AUSTRIA: '🇦🇹',
  DENMARK: '🇩🇰',
  SWEDEN: '🇸🇪',
  NORWAY: '🇳🇴',
  FINLAND: '🇫🇮',
  POLAND: '🇵🇱',
  PORTUGAL: '🇵🇹',
  GREECE: '🇬🇷',
  TURKEY: '🇹🇷',
  RUSSIA: '🇷🇺',
  CHINA: '🇨🇳',
  JAPAN: '🇯🇵',
  'SOUTH KOREA': '🇰🇷',
  KOREA: '🇰🇷',
  INDIA: '🇮🇳',
  THAILAND: '🇹🇭',
  VIETNAM: '🇻🇳',
  INDONESIA: '🇮🇩',
  PHILIPPINES: '🇵🇭',
  MALAYSIA: '🇲🇾',
  SINGAPORE: '🇸🇬',
  AUSTRALIA: '🇦🇺',
  SERBIA: '🇷🇸',
  FIJI: '🇫🇯',
  'NEW ZEALAND': '🇳🇿',
  BRAZIL: '🇧🇷',
  ARGENTINA: '🇦🇷',
  CHILE: '🇨🇱',
  'SOUTH AFRICA': '🇿🇦',
  EGYPT: '🇪🇬',
  ISRAEL: '🇮🇱',
  MOROCCO: '🇲🇦',
  TUNISIA: '🇹🇳',
};

export function countryFlagEmoji(country: string): string {
  return COUNTRY_FLAGS[country.trim().toUpperCase()] || '🌍';
}
