/**
 * Embeds Workstream A v0.14 identity tables + Workstream C v0.4 signal pack into a single TS module
 * for Expo/React Native (no runtime filesystem reads).
 *
 * Run after changing CSV sources:
 *   npm run workstreamC:generate-runtime-bundle
 */

import fs from 'fs';
import path from 'path';
import { parseCsv } from '../src/identity/workstreamA/csv';

const ROOT = path.resolve(__dirname, '..');
const A_INPUT = path.join(ROOT, 'workstreamA', 'a-data', 'wave1-v0.14', 'input');
const C_INPUT = path.join(ROOT, 'workstreamC', 'c-data', 'v0.4', 'input');
const OUT_FILE = path.join(ROOT, 'src', 'workstreamC', 'runtime', 'workstreamCRuntimePack.generated.ts');

function readCsv(filePath: string) {
  return parseCsv(fs.readFileSync(filePath, 'utf8'));
}

function main(): void {
  const brands = readCsv(path.join(A_INPUT, 'canonical_brands.csv'));
  const parents = readCsv(path.join(A_INPUT, 'canonical_parents.csv'));
  const gtins = readCsv(path.join(A_INPUT, 'gtin_brand_links.csv'));
  const links = readCsv(path.join(C_INPUT, 'signal_subject_links.csv'));
  const signals = readCsv(path.join(C_INPUT, 'signal_records.csv'));
  const uxPath = path.join(C_INPUT, 'ux_copy_skeleton.csv');
  const uxRows = fs.existsSync(uxPath) ? readCsv(uxPath) : [];

  const banner = `// AUTO-GENERATED by npm run workstreamC:generate-runtime-bundle — do not edit by hand.

import type { CsvRecord } from '../../identity/workstreamA/csv';

`;

  const body = [
    `export const WORKSTREAM_C_RUNTIME_CANONICAL_BRANDS: CsvRecord[] = ${JSON.stringify(brands)};`,
    `export const WORKSTREAM_C_RUNTIME_CANONICAL_PARENTS: CsvRecord[] = ${JSON.stringify(parents)};`,
    `export const WORKSTREAM_C_RUNTIME_GTIN_BRAND_LINKS: CsvRecord[] = ${JSON.stringify(gtins)};`,
    `export const WORKSTREAM_C_RUNTIME_SIGNAL_SUBJECT_LINKS: CsvRecord[] = ${JSON.stringify(links)};`,
    `export const WORKSTREAM_C_RUNTIME_SIGNAL_RECORDS: CsvRecord[] = ${JSON.stringify(signals)};`,
    `export const WORKSTREAM_C_RUNTIME_UX_COPY_SKELETON: CsvRecord[] = ${JSON.stringify(uxRows)};`,
  ].join('\n\n');

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, `${banner}${body}\n`, 'utf8');
  console.log(`Wrote ${OUT_FILE} (${brands.length} brands, ${gtins.length} gtin links, ${signals.length} signals)`);
}

main();
