import { WORKSTREAM_A_ENUM_DICTIONARY } from './enums';
import { toCsv, type CsvRecord } from './csv';
import { WORKSTREAM_A_FILES, type WorkstreamAFileName } from './schema';

export const WORKSTREAM_A_REQUIRED_FILES: readonly WorkstreamAFileName[] = [
  WORKSTREAM_A_FILES.CANONICAL_PARENTS,
  WORKSTREAM_A_FILES.CANONICAL_BRANDS,
  WORKSTREAM_A_FILES.BRAND_ALIASES,
  WORKSTREAM_A_FILES.GTIN_BRAND_LINKS,
  WORKSTREAM_A_FILES.OPERATIONAL_ENTITIES,
  WORKSTREAM_A_FILES.OWNERSHIP_CHANGE_CANDIDATES,
  WORKSTREAM_A_FILES.STEWARDSHIP_ACTION_LOG,
  WORKSTREAM_A_FILES.SOURCE_REGISTRY,
  WORKSTREAM_A_FILES.ENUM_DICTIONARY,
] as const;

export const WORKSTREAM_A_OPTIONAL_FILES: readonly WorkstreamAFileName[] = [
  WORKSTREAM_A_FILES.WAVE1_CONTROL_SURFACE,
  WORKSTREAM_A_FILES.PARENT_EXTENSION_CANDIDATES,
  WORKSTREAM_A_FILES.ALIAS_HARVEST_CANDIDATES,
  WORKSTREAM_A_FILES.CATALOGUE_AUDIT_OBSERVATIONS,
] as const;

export const WORKSTREAM_A_COLUMNS: Record<WorkstreamAFileName, readonly string[]> = {
  [WORKSTREAM_A_FILES.CANONICAL_PARENTS]: [
    'parent_id',
    'canonical_parent_name',
    'display_parent_name',
    'parent_type',
    'review_state',
    'primary_source_type',
    'primary_source_name',
    'primary_source_id',
    'primary_source_url_or_reference',
    'substantiation_note',
    'parent_operating_role',
    'source_harvest_date',
    'review_owner',
    'review_updated_at',
    'notes_internal',
  ],
  [WORKSTREAM_A_FILES.CANONICAL_BRANDS]: [
    'brand_id',
    'canonical_brand_name',
    'display_brand_name',
    'parent_id',
    'parent_display_name',
    'brand_type',
    'review_state',
    'primary_source_type',
    'primary_source_name',
    'primary_source_id',
    'primary_source_url_or_reference',
    'substantiation_note',
    'source_harvest_date',
    'review_updated_at',
    'notes_internal',
  ],
  [WORKSTREAM_A_FILES.BRAND_ALIASES]: [
    'alias_id',
    'alias_text',
    'alias_normalized',
    'alias_type',
    'alias_source_type',
    'brand_id',
    'canonical_brand_name',
    'parent_id',
    'parent_display_name',
    'review_state',
    'source_reference',
    'source_id',
    'notes_internal',
  ],
  [WORKSTREAM_A_FILES.GTIN_BRAND_LINKS]: [
    'gtin',
    'brand_id',
    'parent_id',
    'link_review_state',
    'source_type',
    'source_reference',
    'source_id',
    'product_name',
    'last_reviewed_at',
    'notes_internal',
  ],
  [WORKSTREAM_A_FILES.OPERATIONAL_ENTITIES]: [
    'operational_entity_id',
    'operational_entity_name',
    'entity_type',
    'use_case_reason',
    'review_state',
    'source_reference',
    'source_id',
    'linked_parent_id',
    'linked_brand_id',
    'notes_internal',
  ],
  [WORKSTREAM_A_FILES.OWNERSHIP_CHANGE_CANDIDATES]: [
    'change_candidate_id',
    'target_entity_type',
    'target_entity_id',
    'candidate_new_parent_name',
    'trigger_source_type',
    'trigger_source_title',
    'trigger_source_url',
    'trigger_source_reference',
    'detected_at',
    'candidate_state',
    'candidate_new_parent_id',
    'human_reviewer',
    'review_outcome_note',
    'approved_effective_date',
    'notes_internal',
    'source_id',
  ],
  [WORKSTREAM_A_FILES.STEWARDSHIP_ACTION_LOG]: [
    'stewardship_action_id',
    'action_type',
    'target_entity_type',
    'target_entity_id',
    'action_timestamp',
    'actor',
    'action_summary',
    'related_change_candidate_id',
    'before_state_note',
    'after_state_note',
  ],
  [WORKSTREAM_A_FILES.SOURCE_REGISTRY]: [
    'source_id',
    'source_name',
    'source_type',
    'source_url_or_reference',
    'source_owner_or_publisher',
    'harvest_method',
    'harvest_date',
    'notes_internal',
  ],
  [WORKSTREAM_A_FILES.ENUM_DICTIONARY]: ['enum_name', 'enum_value'],
  [WORKSTREAM_A_FILES.WAVE1_CONTROL_SURFACE]: [
    'control_row_id',
    'parent_id',
    'canonical_parent_name',
    'parent_cohort_category',
    'au_shelf_priority_y_n',
    'nz_shelf_priority_y_n',
    'bbfaw_seed_asset_member_y_n',
    'ktc_seed_asset_member_y_n',
    'core_uat_asset_member_y_n',
    'official_parent_brand_source_harvested_y_n',
    'source_status',
    'brand_population_status',
    'alias_population_status',
    'gtin_link_status',
    'review_state',
    'gap_status',
    'next_population_action',
    'notes_internal',
  ],
  [WORKSTREAM_A_FILES.PARENT_EXTENSION_CANDIDATES]: [
    'candidate_id',
    'candidate_brand_name',
    'candidate_parent_name',
    'evidence_source_type',
    'evidence_reference',
    'retailer_or_source',
    'category_path',
    'candidate_state',
    'review_outcome_note',
    'notes_internal',
  ],
  [WORKSTREAM_A_FILES.ALIAS_HARVEST_CANDIDATES]: [
    'candidate_id',
    'alias_text',
    'alias_normalized',
    'alias_type',
    'alias_source_type',
    'candidate_brand_id',
    'candidate_canonical_brand_name',
    'candidate_parent_id',
    'candidate_parent_display_name',
    'source_reference',
    'candidate_state',
    'review_outcome_note',
    'notes_internal',
  ],
  [WORKSTREAM_A_FILES.CATALOGUE_AUDIT_OBSERVATIONS]: [
    'audit_row_id',
    'retailer',
    'retailer_country',
    'department',
    'category_path',
    'product_title_raw',
    'extracted_brand_candidate',
    'normalized_brand_candidate',
    'match_status',
    'matched_brand_id',
    'matched_alias_id',
    'parent_extension_candidate_id',
    'audit_date',
    'notes_internal',
  ],
};

export const WORKSTREAM_A_REQUIRED_COLUMNS: Record<WorkstreamAFileName, readonly string[]> = {
  [WORKSTREAM_A_FILES.CANONICAL_PARENTS]: [
    'parent_id',
    'canonical_parent_name',
    'display_parent_name',
    'parent_type',
    'review_state',
    'primary_source_type',
    'primary_source_name',
    'primary_source_id',
    'primary_source_url_or_reference',
    'substantiation_note',
  ],
  [WORKSTREAM_A_FILES.CANONICAL_BRANDS]: [
    'brand_id',
    'canonical_brand_name',
    'display_brand_name',
    'parent_id',
    'parent_display_name',
    'brand_type',
    'review_state',
    'primary_source_type',
    'primary_source_name',
    'primary_source_id',
    'primary_source_url_or_reference',
    'substantiation_note',
  ],
  [WORKSTREAM_A_FILES.BRAND_ALIASES]: [
    'alias_id',
    'alias_text',
    'alias_normalized',
    'alias_type',
    'alias_source_type',
    'brand_id',
    'canonical_brand_name',
    'parent_id',
    'parent_display_name',
    'review_state',
    'source_reference',
  ],
  [WORKSTREAM_A_FILES.GTIN_BRAND_LINKS]: [
    'gtin',
    'brand_id',
    'parent_id',
    'link_review_state',
    'source_type',
    'source_reference',
  ],
  [WORKSTREAM_A_FILES.OPERATIONAL_ENTITIES]: [
    'operational_entity_id',
    'operational_entity_name',
    'entity_type',
    'use_case_reason',
    'review_state',
    'source_reference',
  ],
  [WORKSTREAM_A_FILES.OWNERSHIP_CHANGE_CANDIDATES]: [
    'change_candidate_id',
    'target_entity_type',
    'target_entity_id',
    'candidate_new_parent_name',
    'trigger_source_type',
    'trigger_source_title',
    'trigger_source_reference',
    'detected_at',
    'candidate_state',
  ],
  [WORKSTREAM_A_FILES.STEWARDSHIP_ACTION_LOG]: [
    'stewardship_action_id',
    'action_type',
    'target_entity_type',
    'target_entity_id',
    'action_timestamp',
    'actor',
    'action_summary',
  ],
  [WORKSTREAM_A_FILES.SOURCE_REGISTRY]: [
    'source_id',
    'source_name',
    'source_type',
    'source_url_or_reference',
    'source_owner_or_publisher',
  ],
  [WORKSTREAM_A_FILES.ENUM_DICTIONARY]: ['enum_name', 'enum_value'],
  [WORKSTREAM_A_FILES.WAVE1_CONTROL_SURFACE]: [
    'control_row_id',
    'canonical_parent_name',
    'parent_cohort_category',
    'au_shelf_priority_y_n',
    'nz_shelf_priority_y_n',
    'bbfaw_seed_asset_member_y_n',
    'ktc_seed_asset_member_y_n',
    'core_uat_asset_member_y_n',
    'official_parent_brand_source_harvested_y_n',
    'source_status',
    'brand_population_status',
    'alias_population_status',
    'gtin_link_status',
    'review_state',
    'gap_status',
    'next_population_action',
  ],
  [WORKSTREAM_A_FILES.PARENT_EXTENSION_CANDIDATES]: [
    'candidate_id',
    'candidate_brand_name',
    'candidate_parent_name',
    'evidence_source_type',
    'evidence_reference',
    'retailer_or_source',
    'category_path',
    'candidate_state',
    'review_outcome_note',
  ],
  [WORKSTREAM_A_FILES.ALIAS_HARVEST_CANDIDATES]: [
    'candidate_id',
    'alias_text',
    'alias_normalized',
    'alias_type',
    'alias_source_type',
    'candidate_brand_id',
    'candidate_canonical_brand_name',
    'candidate_parent_id',
    'candidate_parent_display_name',
    'source_reference',
    'candidate_state',
    'review_outcome_note',
  ],
  [WORKSTREAM_A_FILES.CATALOGUE_AUDIT_OBSERVATIONS]: [
    'audit_row_id',
    'retailer',
    'retailer_country',
    'department',
    'category_path',
    'product_title_raw',
    'extracted_brand_candidate',
    'normalized_brand_candidate',
    'match_status',
    'audit_date',
  ],
};

export function buildEnumDictionaryRows(): CsvRecord[] {
  const rows: CsvRecord[] = [];
  for (const [enumName, values] of Object.entries(WORKSTREAM_A_ENUM_DICTIONARY)) {
    for (const enumValue of values) {
      rows.push({ enum_name: enumName, enum_value: enumValue });
    }
  }
  return rows;
}

export function buildTemplateCsvMap(): Record<WorkstreamAFileName, string> {
  const templateMap = {} as Record<WorkstreamAFileName, string>;
  for (const fileName of [...WORKSTREAM_A_REQUIRED_FILES, ...WORKSTREAM_A_OPTIONAL_FILES]) {
    const rows = fileName === WORKSTREAM_A_FILES.ENUM_DICTIONARY ? buildEnumDictionaryRows() : [];
    templateMap[fileName] = toCsv(WORKSTREAM_A_COLUMNS[fileName], rows);
  }
  return templateMap;
}
